version: "3.9"
services:
  db:
    image: mariadb:10.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - "3306:3306"
  wordpress:
    depends_on:
      - db
    build:
      dockerfile: ./wordpress.dockerfile
    ports:
      - "8000:80"
    restart: always
    volumes:
      - ../../:/usr/src/wordpress/wp-content/plugins/urlslab
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: "true"
volumes:
  db_data: {}
