<?php

/**
 * DomainDataRetrievalAugmentRequest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
/**
 * URLSLAB API
 *
 * optimize your website with SEO
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
namespace Urlslab_Vendor\OpenAPI\Client\Model;

use ArrayAccess;
use Urlslab_Vendor\OpenAPI\Client\ObjectSerializer;
/**
 * DomainDataRetrievalAugmentRequest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class DomainDataRetrievalAugmentRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;
    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'domain.dataRetrieval.AugmentRequest';
    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = ['augment_command' => 'string', 'filter' => 'Urlslab_Vendor\\OpenAPI\\Client\\Model\\DomainDataRetrievalContentQuery', 'prompt' => 'Urlslab_Vendor\\OpenAPI\\Client\\Model\\DomainDataRetrievalAugmentPrompt', 'augmenting_model_name' => 'string', 'renew_frequency' => 'string'];
    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = ['augment_command' => null, 'filter' => null, 'prompt' => null, 'augmenting_model_name' => null, 'renew_frequency' => null];
    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = ['augment_command' => \true, 'filter' => \false, 'prompt' => \false, 'augmenting_model_name' => \true, 'renew_frequency' => \false];
    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];
    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }
    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }
    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables() : array
    {
        return self::$openAPINullables;
    }
    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull() : array
    {
        return $this->openAPINullablesSetToNull;
    }
    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull) : void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }
    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property) : bool
    {
        return self::openAPINullables()[$property] ?? \false;
    }
    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property) : bool
    {
        return \in_array($property, $this->getOpenAPINullablesSetToNull(), \true);
    }
    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = ['augment_command' => 'augmentCommand', 'filter' => 'filter', 'prompt' => 'prompt', 'augmenting_model_name' => 'augmentingModelName', 'renew_frequency' => 'renewFrequency'];
    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = ['augment_command' => 'setAugmentCommand', 'filter' => 'setFilter', 'prompt' => 'setPrompt', 'augmenting_model_name' => 'setAugmentingModelName', 'renew_frequency' => 'setRenewFrequency'];
    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = ['augment_command' => 'getAugmentCommand', 'filter' => 'getFilter', 'prompt' => 'getPrompt', 'augmenting_model_name' => 'getAugmentingModelName', 'renew_frequency' => 'getRenewFrequency'];
    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }
    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }
    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }
    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }
    public const AUGMENTING_MODEL_NAME_GPT_4 = 'gpt-4';
    public const AUGMENTING_MODEL_NAME_GPT_3_5_TURBO = 'gpt-3.5-turbo';
    public const AUGMENTING_MODEL_NAME_TEXT_DAVINCI_003 = 'text-davinci-003';
    public const RENEW_FREQUENCY_ONE_TIME = 'ONE_TIME';
    public const RENEW_FREQUENCY_YEARLY = 'YEARLY';
    public const RENEW_FREQUENCY_DAILY = 'DAILY';
    public const RENEW_FREQUENCY_NO_SCHEDULE = 'NO_SCHEDULE';
    public const RENEW_FREQUENCY_WEEKLY = 'WEEKLY';
    public const RENEW_FREQUENCY_HOURLY = 'HOURLY';
    public const RENEW_FREQUENCY_MONTHLY = 'MONTHLY';
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAugmentingModelNameAllowableValues()
    {
        return [self::AUGMENTING_MODEL_NAME_GPT_4, self::AUGMENTING_MODEL_NAME_GPT_3_5_TURBO, self::AUGMENTING_MODEL_NAME_TEXT_DAVINCI_003];
    }
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getRenewFrequencyAllowableValues()
    {
        return [self::RENEW_FREQUENCY_ONE_TIME, self::RENEW_FREQUENCY_YEARLY, self::RENEW_FREQUENCY_DAILY, self::RENEW_FREQUENCY_NO_SCHEDULE, self::RENEW_FREQUENCY_WEEKLY, self::RENEW_FREQUENCY_HOURLY, self::RENEW_FREQUENCY_MONTHLY];
    }
    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];
    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('augment_command', $data ?? [], null);
        $this->setIfExists('filter', $data ?? [], null);
        $this->setIfExists('prompt', $data ?? [], null);
        $this->setIfExists('augmenting_model_name', $data ?? [], null);
        $this->setIfExists('renew_frequency', $data ?? [], null);
    }
    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue) : void
    {
        if (self::isNullable($variableName) && \array_key_exists($variableName, $fields) && \is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }
        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }
    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];
        $allowedValues = $this->getAugmentingModelNameAllowableValues();
        if (!\is_null($this->container['augmenting_model_name']) && !\in_array($this->container['augmenting_model_name'], $allowedValues, \true)) {
            $invalidProperties[] = \sprintf("invalid value '%s' for 'augmenting_model_name', must be one of '%s'", $this->container['augmenting_model_name'], \implode("', '", $allowedValues));
        }
        if ($this->container['renew_frequency'] === null) {
            $invalidProperties[] = "'renew_frequency' can't be null";
        }
        $allowedValues = $this->getRenewFrequencyAllowableValues();
        if (!\is_null($this->container['renew_frequency']) && !\in_array($this->container['renew_frequency'], $allowedValues, \true)) {
            $invalidProperties[] = \sprintf("invalid value '%s' for 'renew_frequency', must be one of '%s'", $this->container['renew_frequency'], \implode("', '", $allowedValues));
        }
        return $invalidProperties;
    }
    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return \count($this->listInvalidProperties()) === 0;
    }
    /**
     * Gets augment_command
     *
     * @return string|null
     */
    public function getAugmentCommand()
    {
        return $this->container['augment_command'];
    }
    /**
     * Sets augment_command
     *
     * @param string|null $augment_command augment_command
     *
     * @return self
     */
    public function setAugmentCommand($augment_command)
    {
        if (\is_null($augment_command)) {
            \array_push($this->openAPINullablesSetToNull, 'augment_command');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = \array_search('augment_command', $nullablesSetToNull);
            if ($index !== \FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['augment_command'] = $augment_command;
        return $this;
    }
    /**
     * Gets filter
     *
     * @return \OpenAPI\Client\Model\DomainDataRetrievalContentQuery|null
     */
    public function getFilter()
    {
        return $this->container['filter'];
    }
    /**
     * Sets filter
     *
     * @param \OpenAPI\Client\Model\DomainDataRetrievalContentQuery|null $filter filter
     *
     * @return self
     */
    public function setFilter($filter)
    {
        if (\is_null($filter)) {
            throw new \InvalidArgumentException('non-nullable filter cannot be null');
        }
        $this->container['filter'] = $filter;
        return $this;
    }
    /**
     * Gets prompt
     *
     * @return \OpenAPI\Client\Model\DomainDataRetrievalAugmentPrompt|null
     */
    public function getPrompt()
    {
        return $this->container['prompt'];
    }
    /**
     * Sets prompt
     *
     * @param \OpenAPI\Client\Model\DomainDataRetrievalAugmentPrompt|null $prompt prompt
     *
     * @return self
     */
    public function setPrompt($prompt)
    {
        if (\is_null($prompt)) {
            throw new \InvalidArgumentException('non-nullable prompt cannot be null');
        }
        $this->container['prompt'] = $prompt;
        return $this;
    }
    /**
     * Gets augmenting_model_name
     *
     * @return string|null
     */
    public function getAugmentingModelName()
    {
        return $this->container['augmenting_model_name'];
    }
    /**
     * Sets augmenting_model_name
     *
     * @param string|null $augmenting_model_name augmenting_model_name
     *
     * @return self
     */
    public function setAugmentingModelName($augmenting_model_name)
    {
        if (\is_null($augmenting_model_name)) {
            \array_push($this->openAPINullablesSetToNull, 'augmenting_model_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = \array_search('augmenting_model_name', $nullablesSetToNull);
            if ($index !== \FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getAugmentingModelNameAllowableValues();
        if (!\is_null($augmenting_model_name) && !\in_array($augmenting_model_name, $allowedValues, \true)) {
            throw new \InvalidArgumentException(\sprintf("Invalid value '%s' for 'augmenting_model_name', must be one of '%s'", $augmenting_model_name, \implode("', '", $allowedValues)));
        }
        $this->container['augmenting_model_name'] = $augmenting_model_name;
        return $this;
    }
    /**
     * Gets renew_frequency
     *
     * @return string
     */
    public function getRenewFrequency()
    {
        return $this->container['renew_frequency'];
    }
    /**
     * Sets renew_frequency
     *
     * @param string $renew_frequency renew_frequency
     *
     * @return self
     */
    public function setRenewFrequency($renew_frequency)
    {
        if (\is_null($renew_frequency)) {
            throw new \InvalidArgumentException('non-nullable renew_frequency cannot be null');
        }
        $allowedValues = $this->getRenewFrequencyAllowableValues();
        if (!\in_array($renew_frequency, $allowedValues, \true)) {
            throw new \InvalidArgumentException(\sprintf("Invalid value '%s' for 'renew_frequency', must be one of '%s'", $renew_frequency, \implode("', '", $allowedValues)));
        }
        $this->container['renew_frequency'] = $renew_frequency;
        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset) : bool
    {
        return isset($this->container[$offset]);
    }
    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }
    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value) : void
    {
        if (\is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }
    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset) : void
    {
        unset($this->container[$offset]);
    }
    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }
    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return \json_encode(ObjectSerializer::sanitizeForSerialization($this), \JSON_PRETTY_PRINT);
    }
    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return \json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
