<?php

/**
 * ApikeyApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
/**
 * URLSLAB API
 *
 * optimize your website with SEO
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */
namespace Urlslab_Vendor\OpenAPI\Client\Test\Api;

use Urlslab_Vendor\OpenAPI\Client\Configuration;
use Urlslab_Vendor\OpenAPI\Client\ApiException;
use Urlslab_Vendor\OpenAPI\Client\ObjectSerializer;
use Urlslab_Vendor\PHPUnit\Framework\TestCase;
/**
 * ApikeyApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ApikeyApiTest extends TestCase
{
    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass() : void
    {
    }
    /**
     * Setup before running each test case
     */
    public function setUp() : void
    {
    }
    /**
     * Clean up after running each test case
     */
    public function tearDown() : void
    {
    }
    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass() : void
    {
    }
    /**
     * Test case for createAPIKey
     *
     * Creates a new API Key for the user.
     *
     */
    public function testCreateAPIKey()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
    /**
     * Test case for deleteAPIKey
     *
     * Deletes an API Key for the user.
     *
     */
    public function testDeleteAPIKey()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
    /**
     * Test case for listAPIKey
     *
     * Lists all API Keys for the user.
     *
     */
    public function testListAPIKey()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
    /**
     * Test case for validate
     *
     * validate a given API Key.
     *
     */
    public function testValidate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
