<?php

/**
 * SnapshotApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
/**
 * URLSLAB API
 *
 * optimize your website with SEO
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */
namespace Urlslab_Vendor\OpenAPI\Client\Test\Api;

use Urlslab_Vendor\OpenAPI\Client\Configuration;
use Urlslab_Vendor\OpenAPI\Client\ApiException;
use Urlslab_Vendor\OpenAPI\Client\ObjectSerializer;
use Urlslab_Vendor\PHPUnit\Framework\TestCase;
/**
 * SnapshotApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SnapshotApiTest extends TestCase
{
    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass() : void
    {
    }
    /**
     * Setup before running each test case
     */
    public function setUp() : void
    {
    }
    /**
     * Clean up after running each test case
     */
    public function tearDown() : void
    {
    }
    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass() : void
    {
    }
    /**
     * Test case for getSnapshots
     *
     * Get screenshot of url.
     *
     */
    public function testGetSnapshots()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
    /**
     * Test case for getSnapshotsHistory
     *
     * Get history of snapshot of url.
     *
     */
    public function testGetSnapshotsHistory()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
