<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = $vendorDir;

return array(
    'Urlslab_Vendor\\Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-message/src'),
    'Urlslab_Vendor\\Psr\\Http\\Client\\' => array($vendorDir . '/psr/http-client/src'),
    'Urlslab_Vendor\\Psr\\Container\\' => array($vendorDir . '/psr/container/src'),
    'Urlslab_Vendor\\OpenAPI\\Client\\' => array($vendorDir . '/urlslab-client/urlslab/urlslab-php-sdk/lib'),
    'Urlslab_Vendor\\GuzzleHttp\\Psr7\\' => array($vendorDir . '/urlslab-client/guzzlehttp/psr7/src'),
    'Urlslab_Vendor\\GuzzleHttp\\Promise\\' => array($vendorDir . '/urlslab-client/guzzlehttp/promises/src'),
    'Urlslab_Vendor\\GuzzleHttp\\' => array($vendorDir . '/urlslab-client/guzzlehttp/guzzle/src'),
);
