<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit494665f8cf896dee738df09758644f90
{
    public static $prefixLengthsPsr4 = array (
        'U' => 
        array (
            'Urlslab_Vendor\\Psr\\Http\\Message\\' => 32,
            'Urlslab_Vendor\\Psr\\Http\\Client\\' => 31,
            'Urlslab_Vendor\\Psr\\Container\\' => 29,
            'Urlslab_Vendor\\OpenAPI\\Client\\' => 30,
            'Urlslab_Vendor\\GuzzleHttp\\Psr7\\' => 31,
            'Urlslab_Vendor\\GuzzleHttp\\Promise\\' => 34,
            'Urlslab_Vendor\\GuzzleHttp\\' => 26,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Urlslab_Vendor\\Psr\\Http\\Message\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/http-message/src',
        ),
        'Urlslab_Vendor\\Psr\\Http\\Client\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/http-client/src',
        ),
        'Urlslab_Vendor\\Psr\\Container\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/container/src',
        ),
        'Urlslab_Vendor\\OpenAPI\\Client\\' => 
        array (
            0 => __DIR__ . '/..' . '/urlslab-client/urlslab/urlslab-php-sdk/lib',
        ),
        'Urlslab_Vendor\\GuzzleHttp\\Psr7\\' => 
        array (
            0 => __DIR__ . '/..' . '/urlslab-client/guzzlehttp/psr7/src',
        ),
        'Urlslab_Vendor\\GuzzleHttp\\Promise\\' => 
        array (
            0 => __DIR__ . '/..' . '/urlslab-client/guzzlehttp/promises/src',
        ),
        'Urlslab_Vendor\\GuzzleHttp\\' => 
        array (
            0 => __DIR__ . '/..' . '/urlslab-client/guzzlehttp/guzzle/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit494665f8cf896dee738df09758644f90::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit494665f8cf896dee738df09758644f90::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit494665f8cf896dee738df09758644f90::$classMap;

        }, null, ClassLoader::class);
    }
}
