<?php
?>
<div class="urlslab-wrap">
	<?php require plugin_dir_path( __FILE__ ) . 'urlslab-admin-header.php'; ?>
	<section class="urlslab-content-container">
		<?php
		$page_data = Urlslab_Page_Factory::get_instance()->get_page( 'urlslab-image-seo' );
		$user = Urlslab_User_Widget::get_instance();
		?>

		<div id="urlslab-vertical-tabs" class="urlslab-container-shadow urlslab-ui-tabs-vertical">
			<ul class="urlslab-tab-topic">
				<li><a href="#fragment-1"><span>Overview</span></a></li>
			</ul>
			<div id="fragment-1">
				<div class="urlslab-tab-content-heading">
					<h3>How it Works?</h3>
					<?php
					$widget = Urlslab_Available_Widgets::get_instance()->get_widget( 'urlslab-image-alt-attribute' );
					require plugin_dir_path( __FILE__ ) . 'urlslab-admin-activation-card-header.php';
					?>
				</div>
				<p>
					Generate Alt text automatically for images that don't have any alt text. The alt text is
					created based on the following:
				</p>
				<ol>
					<li>
						if the Image is wrapped in a link, summary of the destination URL generated by URLSLAB
						will be used as alt text
					</li>
					<li>
						The heading of the article that the image is embeded will be used as alt text
					</li>
				</ol>
			</div>
		</div>
	</section>
</div>
