<?php

class Urlslab_Api_Countries extends Urlslab_Api_Base {
	const SLUG = 'country';

	public function register_routes() {
		$base = '/' . self::SLUG;
		register_rest_route(
			self::NAMESPACE,
			$base . '/',
			array(
				array(
					'methods'             => WP_REST_Server::READABLE,
					'callback'            => array( $this, 'get_items' ),
					'args'                => array(),
					'permission_callback' => array(
						$this,
						'get_items_permissions_check',
					),
				),
			)
		);
	}

	/**
	 * @param WP_REST_Request $request
	 *
	 * @return WP_Error|WP_REST_Response
	 */
	public function get_items( $request ) {
		try {
			$languages = array(
				'af' => 'Afghanistan',
				'ax' => 'Åland Islands',
				'al' => 'Albania',
				'dz' => 'Algeria',
				'as' => 'American Samoa',
				'ad' => 'Andorra',
				'ao' => 'Angola',
				'ai' => 'Anguilla',
				'aq' => 'Antarctica',
				'ag' => 'Antigua and Barbuda',
				'ar' => 'Argentina',
				'am' => 'Armenia',
				'aw' => 'Aruba',
				'au' => 'Australia',
				'at' => 'Austria',
				'az' => 'Azerbaijan',
				'bs' => 'Bahamas',
				'bh' => 'Bahrain',
				'bd' => 'Bangladesh',
				'bb' => 'Barbados',
				'by' => 'Belarus',
				'be' => 'Belgium',
				'bz' => 'Belize',
				'bj' => 'Benin',
				'bm' => 'Bermuda',
				'bt' => 'Bhutan',
				'bo' => 'Bolivia',
				'bq' => 'Bonaire, Sint Eustatius and Saba',
				'ba' => 'Bosnia and Herzegovina',
				'bw' => 'Botswana',
				'bv' => 'Bouvet Island',
				'br' => 'Brazil',
				'io' => 'British Indian Ocean Territory',
				'bn' => 'Brunei Darussalam',
				'bg' => 'Bulgaria',
				'bf' => 'Burkina Faso',
				'bi' => 'Burundi',
				'kh' => 'Cambodia',
				'cm' => 'Cameroon',
				'ca' => 'Canada',
				'cv' => 'Cape Verde',
				'ky' => 'Cayman Islands',
				'cf' => 'Central African Republic',
				'td' => 'Chad',
				'cl' => 'Chile',
				'cn' => 'China',
				'cx' => 'Christmas Island',
				'cc' => 'Cocos (Keeling) Islands',
				'co' => 'Colombia',
				'km' => 'Comoros',
				'cg' => 'Congo',
				'cd' => 'Congo, The Democratic Republic Of The',
				'ck' => 'Cook Islands',
				'cr' => 'Costa Rica',
				'ci' => 'Côte D\'Ivoire',
				'hr' => 'Croatia',
				'cu' => 'Cuba',
				'cw' => 'Curaçao',
				'cy' => 'Cyprus',
				'cz' => 'Czech Republic',
				'dk' => 'Denmark',
				'dj' => 'Djibouti',
				'dm' => 'Dominica',
				'do' => 'Dominican Republic',
				'ec' => 'Ecuador',
				'eg' => 'Egypt',
				'sv' => 'El Salvador',
				'gq' => 'Equatorial Guinea',
				'er' => 'Eritrea',
				'ee' => 'Estonia',
				'et' => 'Ethiopia',
				'fk' => 'Falkland Islands (Malvinas)',
				'fo' => 'Faroe Islands',
				'fj' => 'Fiji',
				'fi' => 'Finland',
				'fr' => 'France',
				'gf' => 'French Guiana',
				'pf' => 'French Polynesia',
				'tf' => 'French Southern Territories',
				'ga' => 'Gabon',
				'gm' => 'Gambia',
				'ge' => 'Georgia',
				'de' => 'Germany',
				'gh' => 'Ghana',
				'gi' => 'Gibraltar',
				'gr' => 'Greece',
				'gl' => 'Greenland',
				'gd' => 'Grenada',
				'gp' => 'Guadeloupe',
				'gu' => 'Guam',
				'gt' => 'Guatemala',
				'gg' => 'Guernsey',
				'gn' => 'Guinea',
				'gw' => 'Guinea-Bissau',
				'gy' => 'Guyana',
				'ht' => 'Haiti',
				'hm' => 'Heard Island and McDonald Islands',
				'va' => 'Holy See (Vatican City State)',
				'hn' => 'Honduras',
				'hk' => 'Hong Kong',
				'hu' => 'Hungary',
				'is' => 'Iceland',
				'in' => 'India',
				'id' => 'Indonesia',
				'ir' => 'Iran, Islamic Republic Of',
				'iq' => 'Iraq',
				'ie' => 'Ireland',
				'im' => 'Isle of Man',
				'il' => 'Israel',
				'it' => 'Italy',
				'jm' => 'Jamaica',
				'jp' => 'Japan',
				'je' => 'Jersey',
				'jo' => 'Jordan',
				'kz' => 'Kazakhstan',
				'ke' => 'Kenya',
				'ki' => 'Kiribati',
				'kp' => 'Korea, Democratic People\'S Republic Of',
				'kr' => 'Korea, Republic of',
				'kw' => 'Kuwait',
				'kg' => 'Kyrgyzstan',
				'la' => 'Lao People\'S Democratic Republic',
				'lv' => 'Latvia',
				'lb' => 'Lebanon',
				'ls' => 'Lesotho',
				'lr' => 'Liberia',
				'ly' => 'Libya',
				'li' => 'Liechtenstein',
				'lt' => 'Lithuania',
				'lu' => 'Luxembourg',
				'mo' => 'Macao',
				'mk' => 'Macedonia, The Former Yugoslav Republic Of',
				'mg' => 'Madagascar',
				'mw' => 'Malawi',
				'my' => 'Malaysia',
				'mv' => 'Maldives',
				'ml' => 'Mali',
				'mt' => 'Malta',
				'mh' => 'Marshall Islands',
				'mq' => 'Martinique',
				'mr' => 'Mauritania',
				'mu' => 'Mauritius',
				'yt' => 'Mayotte',
				'mx' => 'Mexico',
				'fm' => 'Micronesia, Federated States Of',
				'md' => 'Moldova, Republic of',
				'mc' => 'Monaco',
				'mn' => 'Mongolia',
				'me' => 'Montenegro',
				'ms' => 'Montserrat',
				'ma' => 'Morocco',
				'mz' => 'Mozambique',
				'mm' => 'Myanmar',
				'na' => 'Namibia',
				'nr' => 'Nauru',
				'np' => 'Nepal',
				'nl' => 'Netherlands',
				'nc' => 'New Caledonia',
				'nz' => 'New Zealand',
				'ni' => 'Nicaragua',
				'ne' => 'Niger',
				'ng' => 'Nigeria',
				'nu' => 'Niue',
				'nf' => 'Norfolk Island',
				'mp' => 'Northern Mariana Islands',
				'no' => 'Norway',
				'om' => 'Oman',
				'pk' => 'Pakistan',
				'pw' => 'Palau',
				'ps' => 'Palestine, State Of',
				'pa' => 'Panama',
				'pg' => 'Papua New Guinea',
				'py' => 'Paraguay',
				'pe' => 'Peru',
				'ph' => 'Philippines',
				'pn' => 'Pitcairn',
				'pl' => 'Poland',
				'pt' => 'Portugal',
				'pr' => 'Puerto Rico',
				'qa' => 'Qatar',
				're' => 'Réunion',
				'ro' => 'Romania',
				'ru' => 'Russian Federation',
				'rw' => 'Rwanda',
				'bl' => 'Saint Barthélemy',
				'sh' => 'Saint Helena, Ascension and Tristan da Cunha',
				'kn' => 'Saint Kitts and Nevis',
				'lc' => 'Saint Lucia',
				'mf' => 'Saint Martin (French Part)',
				'pm' => 'Saint Pierre and Miquelon',
				'vc' => 'Saint Vincent and The Grenadines',
				'ws' => 'Samoa',
				'sm' => 'San Marino',
				'st' => 'Sao Tome and Principe',
				'sa' => 'Saudi Arabia',
				'sn' => 'Senegal',
				'rs' => 'Serbia',
				'sc' => 'Seychelles',
				'sl' => 'Sierra Leone',
				'sg' => 'Singapore',
				'sx' => 'Sint Maarten (Dutch Part)',
				'sk' => 'Slovakia',
				'si' => 'Slovenia',
				'sb' => 'Solomon Islands',
				'so' => 'Somalia',
				'za' => 'South Africa',
				'gs' => 'South Georgia and The South Sandwich Islands',
				'ss' => 'South Sudan',
				'es' => 'Spain',
				'lk' => 'Sri Lanka',
				'sd' => 'Sudan',
				'sr' => 'Suriname',
				'sj' => 'Svalbard and Jan Mayen',
				'sz' => 'Swaziland',
				'se' => 'Sweden',
				'ch' => 'Switzerland',
				'sy' => 'Syrian Arab Republic',
				'tw' => 'Taiwan',
				'tj' => 'Tajikistan',
				'tz' => 'Tanzania, United Republic Of',
				'th' => 'Thailand',
				'tl' => 'Timor-Leste',
				'tg' => 'Togo',
				'tk' => 'Tokelau',
				'to' => 'Tonga',
				'tt' => 'Trinidad and Tobago',
				'tn' => 'Tunisia',
				'tr' => 'Turkey',
				'tm' => 'Turkmenistan',
				'tc' => 'Turks and Caicos Islands',
				'tv' => 'Tuvalu',
				'ug' => 'Uganda',
				'ua' => 'Ukraine',
				'ae' => 'United Arab Emirates',
				'gb' => 'United Kingdom',
				'us' => 'United States',
				'um' => 'United States Minor Outlying Islands',
				'uy' => 'Uruguay',
				'uz' => 'Uzbekistan',
				'vu' => 'Vanuatu',
				've' => 'Venezuela, Bolivarian Republic of',
				'vn' => 'Viet Nam',
				'vg' => 'Virgin Islands, British',
				'vi' => 'Virgin Islands, U.S.',
				'wf' => 'Wallis and Futuna',
				'eh' => 'Western Sahara',
				'ye' => 'Yemen',
				'zm' => 'Zambia',
				'zw' => 'Zimbabwe',
			);
			foreach ( $languages as $code => $language ) {
				$response_languages[] = (object) array(
					'code' => $code,
					'name' => $language,
				);
			}

			return new WP_REST_Response( $response_languages, 200 );
		} catch ( Exception $e ) {
			return new WP_Error( 'exception', __( 'Failed to get list of modules', 'urlslab' ) );
		}
	}
}
