<?php

/**
 * DocsApi
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
/**
 * URLSLAB API
 *
 * optimize your website with SEO
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
namespace Urlslab_Vendor\OpenAPI\Client\Urlslab;

use Urlslab_Vendor\GuzzleHttp\Client;
use Urlslab_Vendor\GuzzleHttp\ClientInterface;
use Urlslab_Vendor\GuzzleHttp\Exception\ConnectException;
use Urlslab_Vendor\GuzzleHttp\Exception\RequestException;
use Urlslab_Vendor\GuzzleHttp\Psr7\MultipartStream;
use Urlslab_Vendor\GuzzleHttp\Psr7\Request;
use Urlslab_Vendor\GuzzleHttp\RequestOptions;
use Urlslab_Vendor\OpenAPI\Client\ApiException;
use Urlslab_Vendor\OpenAPI\Client\Configuration;
use Urlslab_Vendor\OpenAPI\Client\HeaderSelector;
use Urlslab_Vendor\OpenAPI\Client\ObjectSerializer;
/**
 * DocsApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DocsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;
    /**
     * @var Configuration
     */
    protected $config;
    /**
     * @var HeaderSelector
     */
    protected $headerSelector;
    /**
     * @var int Host index
     */
    protected $hostIndex;
    /** @var string[] $contentTypes **/
    public const contentTypes = ['addDocument' => ['application/json'], 'deleteDocument' => ['text/plain'], 'getDocument' => ['text/plain'], 'searchDocuments' => ['application/json']];
    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(ClientInterface $client = null, Configuration $config = null, HeaderSelector $selector = null, $hostIndex = 0)
    {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }
    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex) : void
    {
        $this->hostIndex = $hostIndex;
    }
    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }
    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }
    /**
     * Operation addDocument
     *
     * Add Custom Document
     *
     * @param  \OpenAPI\Client\Model\DomainDocsDocIndexRequest $domain_docs_doc_index_request Document to be added (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['addDocument'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\DomainAcknowledged
     */
    public function addDocument($domain_docs_doc_index_request, string $contentType = self::contentTypes['addDocument'][0])
    {
        list($response) = $this->addDocumentWithHttpInfo($domain_docs_doc_index_request, $contentType);
        return $response;
    }
    /**
     * Operation addDocumentWithHttpInfo
     *
     * Add Custom Document
     *
     * @param  \OpenAPI\Client\Model\DomainDocsDocIndexRequest $domain_docs_doc_index_request Document to be added (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['addDocument'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\DomainAcknowledged, HTTP status code, HTTP response headers (array of strings)
     */
    public function addDocumentWithHttpInfo($domain_docs_doc_index_request, string $contentType = self::contentTypes['addDocument'][0])
    {
        $request = $this->addDocumentRequest($domain_docs_doc_index_request, $contentType);
        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), $e->getResponse() ? $e->getResponse()->getHeaders() : null, $e->getResponse() ? (string) $e->getResponse()->getBody() : null);
            } catch (ConnectException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), null, null);
            }
            $statusCode = $response->getStatusCode();
            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(\sprintf('[%d] Error connecting to the API (%s)', $statusCode, (string) $request->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
            }
            switch ($statusCode) {
                case 200:
                    if ('\\OpenAPI\\Client\\Model\\DomainAcknowledged' === '\\SplFileObject') {
                        $content = $response->getBody();
                        //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\\OpenAPI\\Client\\Model\\DomainAcknowledged' !== 'string') {
                            $content = \json_decode($content);
                        }
                    }
                    return [ObjectSerializer::deserialize($content, 'Urlslab_Vendor\\OpenAPI\\Client\\Model\\DomainAcknowledged', []), $response->getStatusCode(), $response->getHeaders()];
            }
            $returnType = 'Urlslab_Vendor\\OpenAPI\\Client\\Model\\DomainAcknowledged';
            if ($returnType === '\\SplFileObject') {
                $content = $response->getBody();
                //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = \json_decode($content);
                }
            }
            return [ObjectSerializer::deserialize($content, $returnType, []), $response->getStatusCode(), $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), 'Urlslab_Vendor\\OpenAPI\\Client\\Model\\DomainAcknowledged', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }
    /**
     * Operation addDocumentAsync
     *
     * Add Custom Document
     *
     * @param  \OpenAPI\Client\Model\DomainDocsDocIndexRequest $domain_docs_doc_index_request Document to be added (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['addDocument'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function addDocumentAsync($domain_docs_doc_index_request, string $contentType = self::contentTypes['addDocument'][0])
    {
        return $this->addDocumentAsyncWithHttpInfo($domain_docs_doc_index_request, $contentType)->then(function ($response) {
            return $response[0];
        });
    }
    /**
     * Operation addDocumentAsyncWithHttpInfo
     *
     * Add Custom Document
     *
     * @param  \OpenAPI\Client\Model\DomainDocsDocIndexRequest $domain_docs_doc_index_request Document to be added (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['addDocument'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function addDocumentAsyncWithHttpInfo($domain_docs_doc_index_request, string $contentType = self::contentTypes['addDocument'][0])
    {
        $returnType = 'Urlslab_Vendor\\OpenAPI\\Client\\Model\\DomainAcknowledged';
        $request = $this->addDocumentRequest($domain_docs_doc_index_request, $contentType);
        return $this->client->sendAsync($request, $this->createHttpClientOption())->then(function ($response) use($returnType) {
            if ($returnType === '\\SplFileObject') {
                $content = $response->getBody();
                //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = \json_decode($content);
                }
            }
            return [ObjectSerializer::deserialize($content, $returnType, []), $response->getStatusCode(), $response->getHeaders()];
        }, function ($exception) {
            $response = $exception->getResponse();
            $statusCode = $response->getStatusCode();
            throw new ApiException(\sprintf('[%d] Error connecting to the API (%s)', $statusCode, $exception->getRequest()->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
        });
    }
    /**
     * Create request for operation 'addDocument'
     *
     * @param  \OpenAPI\Client\Model\DomainDocsDocIndexRequest $domain_docs_doc_index_request Document to be added (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['addDocument'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function addDocumentRequest($domain_docs_doc_index_request, string $contentType = self::contentTypes['addDocument'][0])
    {
        // verify the required parameter 'domain_docs_doc_index_request' is set
        if ($domain_docs_doc_index_request === null || \is_array($domain_docs_doc_index_request) && \count($domain_docs_doc_index_request) === 0) {
            throw new \InvalidArgumentException('Missing the required parameter $domain_docs_doc_index_request when calling addDocument');
        }
        $resourcePath = '/v1/content/docs';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = \false;
        $headers = $this->headerSelector->selectHeaders(['application/json'], $contentType, $multipart);
        // for model (json/xml)
        if (isset($domain_docs_doc_index_request)) {
            if (\stripos($headers['Content-Type'], 'application/json') !== \false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \Urlslab_Vendor\GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($domain_docs_doc_index_request));
            } else {
                $httpBody = $domain_docs_doc_index_request;
            }
        } elseif (\count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = \is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = ['name' => $formParamName, 'contents' => $formParamValueItem];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (\stripos($headers['Content-Type'], 'application/json') !== \false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \Urlslab_Vendor\GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-URLSLAB-KEY');
        if ($apiKey !== null) {
            $headers['X-URLSLAB-KEY'] = $apiKey;
        }
        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        $headers = \array_merge($defaultHeaders, $headerParams, $headers);
        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request('PUT', $operationHost . $resourcePath . ($query ? "?{$query}" : ''), $headers, $httpBody);
    }
    /**
     * Operation deleteDocument
     *
     * Delete Document By Id
     *
     * @param  string $id id (required)
     * @param  string $body body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteDocument'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\DomainAcknowledged
     */
    public function deleteDocument($id, $body = null, string $contentType = self::contentTypes['deleteDocument'][0])
    {
        list($response) = $this->deleteDocumentWithHttpInfo($id, $body, $contentType);
        return $response;
    }
    /**
     * Operation deleteDocumentWithHttpInfo
     *
     * Delete Document By Id
     *
     * @param  string $id (required)
     * @param  string $body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteDocument'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\DomainAcknowledged, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteDocumentWithHttpInfo($id, $body = null, string $contentType = self::contentTypes['deleteDocument'][0])
    {
        $request = $this->deleteDocumentRequest($id, $body, $contentType);
        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), $e->getResponse() ? $e->getResponse()->getHeaders() : null, $e->getResponse() ? (string) $e->getResponse()->getBody() : null);
            } catch (ConnectException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), null, null);
            }
            $statusCode = $response->getStatusCode();
            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(\sprintf('[%d] Error connecting to the API (%s)', $statusCode, (string) $request->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
            }
            switch ($statusCode) {
                case 200:
                    if ('\\OpenAPI\\Client\\Model\\DomainAcknowledged' === '\\SplFileObject') {
                        $content = $response->getBody();
                        //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\\OpenAPI\\Client\\Model\\DomainAcknowledged' !== 'string') {
                            $content = \json_decode($content);
                        }
                    }
                    return [ObjectSerializer::deserialize($content, 'Urlslab_Vendor\\OpenAPI\\Client\\Model\\DomainAcknowledged', []), $response->getStatusCode(), $response->getHeaders()];
            }
            $returnType = 'Urlslab_Vendor\\OpenAPI\\Client\\Model\\DomainAcknowledged';
            if ($returnType === '\\SplFileObject') {
                $content = $response->getBody();
                //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = \json_decode($content);
                }
            }
            return [ObjectSerializer::deserialize($content, $returnType, []), $response->getStatusCode(), $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), 'Urlslab_Vendor\\OpenAPI\\Client\\Model\\DomainAcknowledged', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }
    /**
     * Operation deleteDocumentAsync
     *
     * Delete Document By Id
     *
     * @param  string $id (required)
     * @param  string $body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteDocument'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteDocumentAsync($id, $body = null, string $contentType = self::contentTypes['deleteDocument'][0])
    {
        return $this->deleteDocumentAsyncWithHttpInfo($id, $body, $contentType)->then(function ($response) {
            return $response[0];
        });
    }
    /**
     * Operation deleteDocumentAsyncWithHttpInfo
     *
     * Delete Document By Id
     *
     * @param  string $id (required)
     * @param  string $body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteDocument'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteDocumentAsyncWithHttpInfo($id, $body = null, string $contentType = self::contentTypes['deleteDocument'][0])
    {
        $returnType = 'Urlslab_Vendor\\OpenAPI\\Client\\Model\\DomainAcknowledged';
        $request = $this->deleteDocumentRequest($id, $body, $contentType);
        return $this->client->sendAsync($request, $this->createHttpClientOption())->then(function ($response) use($returnType) {
            if ($returnType === '\\SplFileObject') {
                $content = $response->getBody();
                //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = \json_decode($content);
                }
            }
            return [ObjectSerializer::deserialize($content, $returnType, []), $response->getStatusCode(), $response->getHeaders()];
        }, function ($exception) {
            $response = $exception->getResponse();
            $statusCode = $response->getStatusCode();
            throw new ApiException(\sprintf('[%d] Error connecting to the API (%s)', $statusCode, $exception->getRequest()->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
        });
    }
    /**
     * Create request for operation 'deleteDocument'
     *
     * @param  string $id (required)
     * @param  string $body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteDocument'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deleteDocumentRequest($id, $body = null, string $contentType = self::contentTypes['deleteDocument'][0])
    {
        // verify the required parameter 'id' is set
        if ($id === null || \is_array($id) && \count($id) === 0) {
            throw new \InvalidArgumentException('Missing the required parameter $id when calling deleteDocument');
        }
        $resourcePath = '/v1/content/docs/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = \false;
        // path params
        if ($id !== null) {
            $resourcePath = \str_replace('{' . 'id' . '}', ObjectSerializer::toPathValue($id), $resourcePath);
        }
        $headers = $this->headerSelector->selectHeaders(['application/json'], $contentType, $multipart);
        // for model (json/xml)
        if (isset($body)) {
            if (\stripos($headers['Content-Type'], 'application/json') !== \false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \Urlslab_Vendor\GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($body));
            } else {
                $httpBody = $body;
            }
        } elseif (\count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = \is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = ['name' => $formParamName, 'contents' => $formParamValueItem];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (\stripos($headers['Content-Type'], 'application/json') !== \false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \Urlslab_Vendor\GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-URLSLAB-KEY');
        if ($apiKey !== null) {
            $headers['X-URLSLAB-KEY'] = $apiKey;
        }
        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        $headers = \array_merge($defaultHeaders, $headerParams, $headers);
        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request('DELETE', $operationHost . $resourcePath . ($query ? "?{$query}" : ''), $headers, $httpBody);
    }
    /**
     * Operation getDocument
     *
     * Get Document By Id
     *
     * @param  string $id id (required)
     * @param  string $body body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDocument'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\DomainDocsDocResponse
     */
    public function getDocument($id, $body = null, string $contentType = self::contentTypes['getDocument'][0])
    {
        list($response) = $this->getDocumentWithHttpInfo($id, $body, $contentType);
        return $response;
    }
    /**
     * Operation getDocumentWithHttpInfo
     *
     * Get Document By Id
     *
     * @param  string $id (required)
     * @param  string $body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDocument'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\DomainDocsDocResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getDocumentWithHttpInfo($id, $body = null, string $contentType = self::contentTypes['getDocument'][0])
    {
        $request = $this->getDocumentRequest($id, $body, $contentType);
        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), $e->getResponse() ? $e->getResponse()->getHeaders() : null, $e->getResponse() ? (string) $e->getResponse()->getBody() : null);
            } catch (ConnectException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), null, null);
            }
            $statusCode = $response->getStatusCode();
            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(\sprintf('[%d] Error connecting to the API (%s)', $statusCode, (string) $request->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
            }
            switch ($statusCode) {
                case 200:
                    if ('\\OpenAPI\\Client\\Model\\DomainDocsDocResponse' === '\\SplFileObject') {
                        $content = $response->getBody();
                        //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\\OpenAPI\\Client\\Model\\DomainDocsDocResponse' !== 'string') {
                            $content = \json_decode($content);
                        }
                    }
                    return [ObjectSerializer::deserialize($content, 'Urlslab_Vendor\\OpenAPI\\Client\\Model\\DomainDocsDocResponse', []), $response->getStatusCode(), $response->getHeaders()];
            }
            $returnType = 'Urlslab_Vendor\\OpenAPI\\Client\\Model\\DomainDocsDocResponse';
            if ($returnType === '\\SplFileObject') {
                $content = $response->getBody();
                //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = \json_decode($content);
                }
            }
            return [ObjectSerializer::deserialize($content, $returnType, []), $response->getStatusCode(), $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), 'Urlslab_Vendor\\OpenAPI\\Client\\Model\\DomainDocsDocResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }
    /**
     * Operation getDocumentAsync
     *
     * Get Document By Id
     *
     * @param  string $id (required)
     * @param  string $body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDocument'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getDocumentAsync($id, $body = null, string $contentType = self::contentTypes['getDocument'][0])
    {
        return $this->getDocumentAsyncWithHttpInfo($id, $body, $contentType)->then(function ($response) {
            return $response[0];
        });
    }
    /**
     * Operation getDocumentAsyncWithHttpInfo
     *
     * Get Document By Id
     *
     * @param  string $id (required)
     * @param  string $body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDocument'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getDocumentAsyncWithHttpInfo($id, $body = null, string $contentType = self::contentTypes['getDocument'][0])
    {
        $returnType = 'Urlslab_Vendor\\OpenAPI\\Client\\Model\\DomainDocsDocResponse';
        $request = $this->getDocumentRequest($id, $body, $contentType);
        return $this->client->sendAsync($request, $this->createHttpClientOption())->then(function ($response) use($returnType) {
            if ($returnType === '\\SplFileObject') {
                $content = $response->getBody();
                //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = \json_decode($content);
                }
            }
            return [ObjectSerializer::deserialize($content, $returnType, []), $response->getStatusCode(), $response->getHeaders()];
        }, function ($exception) {
            $response = $exception->getResponse();
            $statusCode = $response->getStatusCode();
            throw new ApiException(\sprintf('[%d] Error connecting to the API (%s)', $statusCode, $exception->getRequest()->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
        });
    }
    /**
     * Create request for operation 'getDocument'
     *
     * @param  string $id (required)
     * @param  string $body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDocument'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getDocumentRequest($id, $body = null, string $contentType = self::contentTypes['getDocument'][0])
    {
        // verify the required parameter 'id' is set
        if ($id === null || \is_array($id) && \count($id) === 0) {
            throw new \InvalidArgumentException('Missing the required parameter $id when calling getDocument');
        }
        $resourcePath = '/v1/content/docs/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = \false;
        // path params
        if ($id !== null) {
            $resourcePath = \str_replace('{' . 'id' . '}', ObjectSerializer::toPathValue($id), $resourcePath);
        }
        $headers = $this->headerSelector->selectHeaders(['application/json'], $contentType, $multipart);
        // for model (json/xml)
        if (isset($body)) {
            if (\stripos($headers['Content-Type'], 'application/json') !== \false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \Urlslab_Vendor\GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($body));
            } else {
                $httpBody = $body;
            }
        } elseif (\count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = \is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = ['name' => $formParamName, 'contents' => $formParamValueItem];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (\stripos($headers['Content-Type'], 'application/json') !== \false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \Urlslab_Vendor\GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-URLSLAB-KEY');
        if ($apiKey !== null) {
            $headers['X-URLSLAB-KEY'] = $apiKey;
        }
        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        $headers = \array_merge($defaultHeaders, $headerParams, $headers);
        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request('GET', $operationHost . $resourcePath . ($query ? "?{$query}" : ''), $headers, $httpBody);
    }
    /**
     * Operation searchDocuments
     *
     * Get All Documents
     *
     * @param  \OpenAPI\Client\Model\DomainDocsSearchRequest $domain_docs_search_request search parameters (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchDocuments'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\DomainDocsDocResponse
     */
    public function searchDocuments($domain_docs_search_request, string $contentType = self::contentTypes['searchDocuments'][0])
    {
        list($response) = $this->searchDocumentsWithHttpInfo($domain_docs_search_request, $contentType);
        return $response;
    }
    /**
     * Operation searchDocumentsWithHttpInfo
     *
     * Get All Documents
     *
     * @param  \OpenAPI\Client\Model\DomainDocsSearchRequest $domain_docs_search_request search parameters (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchDocuments'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\DomainDocsDocResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function searchDocumentsWithHttpInfo($domain_docs_search_request, string $contentType = self::contentTypes['searchDocuments'][0])
    {
        $request = $this->searchDocumentsRequest($domain_docs_search_request, $contentType);
        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), $e->getResponse() ? $e->getResponse()->getHeaders() : null, $e->getResponse() ? (string) $e->getResponse()->getBody() : null);
            } catch (ConnectException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), null, null);
            }
            $statusCode = $response->getStatusCode();
            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(\sprintf('[%d] Error connecting to the API (%s)', $statusCode, (string) $request->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
            }
            switch ($statusCode) {
                case 200:
                    if ('\\OpenAPI\\Client\\Model\\DomainDocsDocResponse' === '\\SplFileObject') {
                        $content = $response->getBody();
                        //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\\OpenAPI\\Client\\Model\\DomainDocsDocResponse' !== 'string') {
                            $content = \json_decode($content);
                        }
                    }
                    return [ObjectSerializer::deserialize($content, 'Urlslab_Vendor\\OpenAPI\\Client\\Model\\DomainDocsDocResponse', []), $response->getStatusCode(), $response->getHeaders()];
            }
            $returnType = 'Urlslab_Vendor\\OpenAPI\\Client\\Model\\DomainDocsDocResponse';
            if ($returnType === '\\SplFileObject') {
                $content = $response->getBody();
                //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = \json_decode($content);
                }
            }
            return [ObjectSerializer::deserialize($content, $returnType, []), $response->getStatusCode(), $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), 'Urlslab_Vendor\\OpenAPI\\Client\\Model\\DomainDocsDocResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }
    /**
     * Operation searchDocumentsAsync
     *
     * Get All Documents
     *
     * @param  \OpenAPI\Client\Model\DomainDocsSearchRequest $domain_docs_search_request search parameters (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchDocuments'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchDocumentsAsync($domain_docs_search_request, string $contentType = self::contentTypes['searchDocuments'][0])
    {
        return $this->searchDocumentsAsyncWithHttpInfo($domain_docs_search_request, $contentType)->then(function ($response) {
            return $response[0];
        });
    }
    /**
     * Operation searchDocumentsAsyncWithHttpInfo
     *
     * Get All Documents
     *
     * @param  \OpenAPI\Client\Model\DomainDocsSearchRequest $domain_docs_search_request search parameters (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchDocuments'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchDocumentsAsyncWithHttpInfo($domain_docs_search_request, string $contentType = self::contentTypes['searchDocuments'][0])
    {
        $returnType = 'Urlslab_Vendor\\OpenAPI\\Client\\Model\\DomainDocsDocResponse';
        $request = $this->searchDocumentsRequest($domain_docs_search_request, $contentType);
        return $this->client->sendAsync($request, $this->createHttpClientOption())->then(function ($response) use($returnType) {
            if ($returnType === '\\SplFileObject') {
                $content = $response->getBody();
                //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = \json_decode($content);
                }
            }
            return [ObjectSerializer::deserialize($content, $returnType, []), $response->getStatusCode(), $response->getHeaders()];
        }, function ($exception) {
            $response = $exception->getResponse();
            $statusCode = $response->getStatusCode();
            throw new ApiException(\sprintf('[%d] Error connecting to the API (%s)', $statusCode, $exception->getRequest()->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
        });
    }
    /**
     * Create request for operation 'searchDocuments'
     *
     * @param  \OpenAPI\Client\Model\DomainDocsSearchRequest $domain_docs_search_request search parameters (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchDocuments'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function searchDocumentsRequest($domain_docs_search_request, string $contentType = self::contentTypes['searchDocuments'][0])
    {
        // verify the required parameter 'domain_docs_search_request' is set
        if ($domain_docs_search_request === null || \is_array($domain_docs_search_request) && \count($domain_docs_search_request) === 0) {
            throw new \InvalidArgumentException('Missing the required parameter $domain_docs_search_request when calling searchDocuments');
        }
        $resourcePath = '/v1/content/docs';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = \false;
        $headers = $this->headerSelector->selectHeaders(['application/json'], $contentType, $multipart);
        // for model (json/xml)
        if (isset($domain_docs_search_request)) {
            if (\stripos($headers['Content-Type'], 'application/json') !== \false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \Urlslab_Vendor\GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($domain_docs_search_request));
            } else {
                $httpBody = $domain_docs_search_request;
            }
        } elseif (\count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = \is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = ['name' => $formParamName, 'contents' => $formParamValueItem];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (\stripos($headers['Content-Type'], 'application/json') !== \false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \Urlslab_Vendor\GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-URLSLAB-KEY');
        if ($apiKey !== null) {
            $headers['X-URLSLAB-KEY'] = $apiKey;
        }
        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        $headers = \array_merge($defaultHeaders, $headerParams, $headers);
        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request('POST', $operationHost . $resourcePath . ($query ? "?{$query}" : ''), $headers, $httpBody);
    }
    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = \fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }
        return $options;
    }
}
