<?php

/**
 * PublicAssetsApi
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
/**
 * URLSLAB API
 *
 * optimize your website with SEO
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
namespace Urlslab_Vendor\OpenAPI\Client\Urlslab;

use Urlslab_Vendor\GuzzleHttp\Client;
use Urlslab_Vendor\GuzzleHttp\ClientInterface;
use Urlslab_Vendor\GuzzleHttp\Exception\ConnectException;
use Urlslab_Vendor\GuzzleHttp\Exception\RequestException;
use Urlslab_Vendor\GuzzleHttp\Psr7\MultipartStream;
use Urlslab_Vendor\GuzzleHttp\Psr7\Request;
use Urlslab_Vendor\GuzzleHttp\RequestOptions;
use Urlslab_Vendor\OpenAPI\Client\ApiException;
use Urlslab_Vendor\OpenAPI\Client\Configuration;
use Urlslab_Vendor\OpenAPI\Client\HeaderSelector;
use Urlslab_Vendor\OpenAPI\Client\ObjectSerializer;
/**
 * PublicAssetsApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PublicAssetsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;
    /**
     * @var Configuration
     */
    protected $config;
    /**
     * @var HeaderSelector
     */
    protected $headerSelector;
    /**
     * @var int Host index
     */
    protected $hostIndex;
    /** @var string[] $contentTypes **/
    public const contentTypes = ['loadCarouselThumbnail' => ['text/plain'], 'loadFullPageThumbnail' => ['text/plain'], 'loadImageCarousel' => ['text/plain'], 'loadOriginalImage' => ['text/plain'], 'loadTechnologyLogo' => ['text/plain']];
    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(ClientInterface $client = null, Configuration $config = null, HeaderSelector $selector = null, $hostIndex = 0)
    {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }
    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex) : void
    {
        $this->hostIndex = $hostIndex;
    }
    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }
    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }
    /**
     * Operation loadCarouselThumbnail
     *
     * Fetching thumbnail of carousel screenshot of url
     *
     * @param  string $bucket_id bucket_id (required)
     * @param  string $body API Key to be validated (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loadCarouselThumbnail'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \SplFileObject
     */
    public function loadCarouselThumbnail($bucket_id, $body = null, string $contentType = self::contentTypes['loadCarouselThumbnail'][0])
    {
        list($response) = $this->loadCarouselThumbnailWithHttpInfo($bucket_id, $body, $contentType);
        return $response;
    }
    /**
     * Operation loadCarouselThumbnailWithHttpInfo
     *
     * Fetching thumbnail of carousel screenshot of url
     *
     * @param  string $bucket_id (required)
     * @param  string $body API Key to be validated (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loadCarouselThumbnail'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \SplFileObject, HTTP status code, HTTP response headers (array of strings)
     */
    public function loadCarouselThumbnailWithHttpInfo($bucket_id, $body = null, string $contentType = self::contentTypes['loadCarouselThumbnail'][0])
    {
        $request = $this->loadCarouselThumbnailRequest($bucket_id, $body, $contentType);
        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), $e->getResponse() ? $e->getResponse()->getHeaders() : null, $e->getResponse() ? (string) $e->getResponse()->getBody() : null);
            } catch (ConnectException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), null, null);
            }
            $statusCode = $response->getStatusCode();
            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(\sprintf('[%d] Error connecting to the API (%s)', $statusCode, (string) $request->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
            }
            switch ($statusCode) {
                case 200:
                    if ('\\SplFileObject' === '\\SplFileObject') {
                        $content = $response->getBody();
                        //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\\SplFileObject' !== 'string') {
                            $content = \json_decode($content);
                        }
                    }
                    return [ObjectSerializer::deserialize($content, '\\SplFileObject', []), $response->getStatusCode(), $response->getHeaders()];
            }
            $returnType = '\\SplFileObject';
            if ($returnType === '\\SplFileObject') {
                $content = $response->getBody();
                //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = \json_decode($content);
                }
            }
            return [ObjectSerializer::deserialize($content, $returnType, []), $response->getStatusCode(), $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\\SplFileObject', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }
    /**
     * Operation loadCarouselThumbnailAsync
     *
     * Fetching thumbnail of carousel screenshot of url
     *
     * @param  string $bucket_id (required)
     * @param  string $body API Key to be validated (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loadCarouselThumbnail'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function loadCarouselThumbnailAsync($bucket_id, $body = null, string $contentType = self::contentTypes['loadCarouselThumbnail'][0])
    {
        return $this->loadCarouselThumbnailAsyncWithHttpInfo($bucket_id, $body, $contentType)->then(function ($response) {
            return $response[0];
        });
    }
    /**
     * Operation loadCarouselThumbnailAsyncWithHttpInfo
     *
     * Fetching thumbnail of carousel screenshot of url
     *
     * @param  string $bucket_id (required)
     * @param  string $body API Key to be validated (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loadCarouselThumbnail'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function loadCarouselThumbnailAsyncWithHttpInfo($bucket_id, $body = null, string $contentType = self::contentTypes['loadCarouselThumbnail'][0])
    {
        $returnType = '\\SplFileObject';
        $request = $this->loadCarouselThumbnailRequest($bucket_id, $body, $contentType);
        return $this->client->sendAsync($request, $this->createHttpClientOption())->then(function ($response) use($returnType) {
            if ($returnType === '\\SplFileObject') {
                $content = $response->getBody();
                //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = \json_decode($content);
                }
            }
            return [ObjectSerializer::deserialize($content, $returnType, []), $response->getStatusCode(), $response->getHeaders()];
        }, function ($exception) {
            $response = $exception->getResponse();
            $statusCode = $response->getStatusCode();
            throw new ApiException(\sprintf('[%d] Error connecting to the API (%s)', $statusCode, $exception->getRequest()->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
        });
    }
    /**
     * Create request for operation 'loadCarouselThumbnail'
     *
     * @param  string $bucket_id (required)
     * @param  string $body API Key to be validated (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loadCarouselThumbnail'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function loadCarouselThumbnailRequest($bucket_id, $body = null, string $contentType = self::contentTypes['loadCarouselThumbnail'][0])
    {
        // verify the required parameter 'bucket_id' is set
        if ($bucket_id === null || \is_array($bucket_id) && \count($bucket_id) === 0) {
            throw new \InvalidArgumentException('Missing the required parameter $bucket_id when calling loadCarouselThumbnail');
        }
        $resourcePath = '/v1/public/screenshot/thumbnail/carousel/{bucketId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = \false;
        // path params
        if ($bucket_id !== null) {
            $resourcePath = \str_replace('{' . 'bucketId' . '}', ObjectSerializer::toPathValue($bucket_id), $resourcePath);
        }
        $headers = $this->headerSelector->selectHeaders(['image/png'], $contentType, $multipart);
        // for model (json/xml)
        if (isset($body)) {
            if (\stripos($headers['Content-Type'], 'application/json') !== \false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \Urlslab_Vendor\GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($body));
            } else {
                $httpBody = $body;
            }
        } elseif (\count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = \is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = ['name' => $formParamName, 'contents' => $formParamValueItem];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (\stripos($headers['Content-Type'], 'application/json') !== \false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \Urlslab_Vendor\GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-URLSLAB-KEY');
        if ($apiKey !== null) {
            $headers['X-URLSLAB-KEY'] = $apiKey;
        }
        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        $headers = \array_merge($defaultHeaders, $headerParams, $headers);
        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request('GET', $operationHost . $resourcePath . ($query ? "?{$query}" : ''), $headers, $httpBody);
    }
    /**
     * Operation loadFullPageThumbnail
     *
     * Fetching thumbnail of fullpage screenshot of url
     *
     * @param  string $bucket_id bucket_id (required)
     * @param  string $body API Key to be validated (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loadFullPageThumbnail'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \SplFileObject
     */
    public function loadFullPageThumbnail($bucket_id, $body = null, string $contentType = self::contentTypes['loadFullPageThumbnail'][0])
    {
        list($response) = $this->loadFullPageThumbnailWithHttpInfo($bucket_id, $body, $contentType);
        return $response;
    }
    /**
     * Operation loadFullPageThumbnailWithHttpInfo
     *
     * Fetching thumbnail of fullpage screenshot of url
     *
     * @param  string $bucket_id (required)
     * @param  string $body API Key to be validated (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loadFullPageThumbnail'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \SplFileObject, HTTP status code, HTTP response headers (array of strings)
     */
    public function loadFullPageThumbnailWithHttpInfo($bucket_id, $body = null, string $contentType = self::contentTypes['loadFullPageThumbnail'][0])
    {
        $request = $this->loadFullPageThumbnailRequest($bucket_id, $body, $contentType);
        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), $e->getResponse() ? $e->getResponse()->getHeaders() : null, $e->getResponse() ? (string) $e->getResponse()->getBody() : null);
            } catch (ConnectException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), null, null);
            }
            $statusCode = $response->getStatusCode();
            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(\sprintf('[%d] Error connecting to the API (%s)', $statusCode, (string) $request->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
            }
            switch ($statusCode) {
                case 200:
                    if ('\\SplFileObject' === '\\SplFileObject') {
                        $content = $response->getBody();
                        //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\\SplFileObject' !== 'string') {
                            $content = \json_decode($content);
                        }
                    }
                    return [ObjectSerializer::deserialize($content, '\\SplFileObject', []), $response->getStatusCode(), $response->getHeaders()];
            }
            $returnType = '\\SplFileObject';
            if ($returnType === '\\SplFileObject') {
                $content = $response->getBody();
                //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = \json_decode($content);
                }
            }
            return [ObjectSerializer::deserialize($content, $returnType, []), $response->getStatusCode(), $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\\SplFileObject', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }
    /**
     * Operation loadFullPageThumbnailAsync
     *
     * Fetching thumbnail of fullpage screenshot of url
     *
     * @param  string $bucket_id (required)
     * @param  string $body API Key to be validated (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loadFullPageThumbnail'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function loadFullPageThumbnailAsync($bucket_id, $body = null, string $contentType = self::contentTypes['loadFullPageThumbnail'][0])
    {
        return $this->loadFullPageThumbnailAsyncWithHttpInfo($bucket_id, $body, $contentType)->then(function ($response) {
            return $response[0];
        });
    }
    /**
     * Operation loadFullPageThumbnailAsyncWithHttpInfo
     *
     * Fetching thumbnail of fullpage screenshot of url
     *
     * @param  string $bucket_id (required)
     * @param  string $body API Key to be validated (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loadFullPageThumbnail'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function loadFullPageThumbnailAsyncWithHttpInfo($bucket_id, $body = null, string $contentType = self::contentTypes['loadFullPageThumbnail'][0])
    {
        $returnType = '\\SplFileObject';
        $request = $this->loadFullPageThumbnailRequest($bucket_id, $body, $contentType);
        return $this->client->sendAsync($request, $this->createHttpClientOption())->then(function ($response) use($returnType) {
            if ($returnType === '\\SplFileObject') {
                $content = $response->getBody();
                //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = \json_decode($content);
                }
            }
            return [ObjectSerializer::deserialize($content, $returnType, []), $response->getStatusCode(), $response->getHeaders()];
        }, function ($exception) {
            $response = $exception->getResponse();
            $statusCode = $response->getStatusCode();
            throw new ApiException(\sprintf('[%d] Error connecting to the API (%s)', $statusCode, $exception->getRequest()->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
        });
    }
    /**
     * Create request for operation 'loadFullPageThumbnail'
     *
     * @param  string $bucket_id (required)
     * @param  string $body API Key to be validated (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loadFullPageThumbnail'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function loadFullPageThumbnailRequest($bucket_id, $body = null, string $contentType = self::contentTypes['loadFullPageThumbnail'][0])
    {
        // verify the required parameter 'bucket_id' is set
        if ($bucket_id === null || \is_array($bucket_id) && \count($bucket_id) === 0) {
            throw new \InvalidArgumentException('Missing the required parameter $bucket_id when calling loadFullPageThumbnail');
        }
        $resourcePath = '/v1/public/screenshot/thumbnail/fullpage/{bucketId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = \false;
        // path params
        if ($bucket_id !== null) {
            $resourcePath = \str_replace('{' . 'bucketId' . '}', ObjectSerializer::toPathValue($bucket_id), $resourcePath);
        }
        $headers = $this->headerSelector->selectHeaders(['image/png'], $contentType, $multipart);
        // for model (json/xml)
        if (isset($body)) {
            if (\stripos($headers['Content-Type'], 'application/json') !== \false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \Urlslab_Vendor\GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($body));
            } else {
                $httpBody = $body;
            }
        } elseif (\count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = \is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = ['name' => $formParamName, 'contents' => $formParamValueItem];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (\stripos($headers['Content-Type'], 'application/json') !== \false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \Urlslab_Vendor\GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-URLSLAB-KEY');
        if ($apiKey !== null) {
            $headers['X-URLSLAB-KEY'] = $apiKey;
        }
        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        $headers = \array_merge($defaultHeaders, $headerParams, $headers);
        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request('GET', $operationHost . $resourcePath . ($query ? "?{$query}" : ''), $headers, $httpBody);
    }
    /**
     * Operation loadImageCarousel
     *
     * Fetching carousel screenshot of url
     *
     * @param  string $bucket_id bucket_id (required)
     * @param  string $body API Key to be validated (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loadImageCarousel'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \SplFileObject
     */
    public function loadImageCarousel($bucket_id, $body = null, string $contentType = self::contentTypes['loadImageCarousel'][0])
    {
        list($response) = $this->loadImageCarouselWithHttpInfo($bucket_id, $body, $contentType);
        return $response;
    }
    /**
     * Operation loadImageCarouselWithHttpInfo
     *
     * Fetching carousel screenshot of url
     *
     * @param  string $bucket_id (required)
     * @param  string $body API Key to be validated (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loadImageCarousel'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \SplFileObject, HTTP status code, HTTP response headers (array of strings)
     */
    public function loadImageCarouselWithHttpInfo($bucket_id, $body = null, string $contentType = self::contentTypes['loadImageCarousel'][0])
    {
        $request = $this->loadImageCarouselRequest($bucket_id, $body, $contentType);
        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), $e->getResponse() ? $e->getResponse()->getHeaders() : null, $e->getResponse() ? (string) $e->getResponse()->getBody() : null);
            } catch (ConnectException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), null, null);
            }
            $statusCode = $response->getStatusCode();
            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(\sprintf('[%d] Error connecting to the API (%s)', $statusCode, (string) $request->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
            }
            switch ($statusCode) {
                case 200:
                    if ('\\SplFileObject' === '\\SplFileObject') {
                        $content = $response->getBody();
                        //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\\SplFileObject' !== 'string') {
                            $content = \json_decode($content);
                        }
                    }
                    return [ObjectSerializer::deserialize($content, '\\SplFileObject', []), $response->getStatusCode(), $response->getHeaders()];
            }
            $returnType = '\\SplFileObject';
            if ($returnType === '\\SplFileObject') {
                $content = $response->getBody();
                //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = \json_decode($content);
                }
            }
            return [ObjectSerializer::deserialize($content, $returnType, []), $response->getStatusCode(), $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\\SplFileObject', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }
    /**
     * Operation loadImageCarouselAsync
     *
     * Fetching carousel screenshot of url
     *
     * @param  string $bucket_id (required)
     * @param  string $body API Key to be validated (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loadImageCarousel'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function loadImageCarouselAsync($bucket_id, $body = null, string $contentType = self::contentTypes['loadImageCarousel'][0])
    {
        return $this->loadImageCarouselAsyncWithHttpInfo($bucket_id, $body, $contentType)->then(function ($response) {
            return $response[0];
        });
    }
    /**
     * Operation loadImageCarouselAsyncWithHttpInfo
     *
     * Fetching carousel screenshot of url
     *
     * @param  string $bucket_id (required)
     * @param  string $body API Key to be validated (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loadImageCarousel'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function loadImageCarouselAsyncWithHttpInfo($bucket_id, $body = null, string $contentType = self::contentTypes['loadImageCarousel'][0])
    {
        $returnType = '\\SplFileObject';
        $request = $this->loadImageCarouselRequest($bucket_id, $body, $contentType);
        return $this->client->sendAsync($request, $this->createHttpClientOption())->then(function ($response) use($returnType) {
            if ($returnType === '\\SplFileObject') {
                $content = $response->getBody();
                //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = \json_decode($content);
                }
            }
            return [ObjectSerializer::deserialize($content, $returnType, []), $response->getStatusCode(), $response->getHeaders()];
        }, function ($exception) {
            $response = $exception->getResponse();
            $statusCode = $response->getStatusCode();
            throw new ApiException(\sprintf('[%d] Error connecting to the API (%s)', $statusCode, $exception->getRequest()->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
        });
    }
    /**
     * Create request for operation 'loadImageCarousel'
     *
     * @param  string $bucket_id (required)
     * @param  string $body API Key to be validated (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loadImageCarousel'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function loadImageCarouselRequest($bucket_id, $body = null, string $contentType = self::contentTypes['loadImageCarousel'][0])
    {
        // verify the required parameter 'bucket_id' is set
        if ($bucket_id === null || \is_array($bucket_id) && \count($bucket_id) === 0) {
            throw new \InvalidArgumentException('Missing the required parameter $bucket_id when calling loadImageCarousel');
        }
        $resourcePath = '/v1/public/screenshot/carousel/{bucketId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = \false;
        // path params
        if ($bucket_id !== null) {
            $resourcePath = \str_replace('{' . 'bucketId' . '}', ObjectSerializer::toPathValue($bucket_id), $resourcePath);
        }
        $headers = $this->headerSelector->selectHeaders(['image/png'], $contentType, $multipart);
        // for model (json/xml)
        if (isset($body)) {
            if (\stripos($headers['Content-Type'], 'application/json') !== \false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \Urlslab_Vendor\GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($body));
            } else {
                $httpBody = $body;
            }
        } elseif (\count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = \is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = ['name' => $formParamName, 'contents' => $formParamValueItem];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (\stripos($headers['Content-Type'], 'application/json') !== \false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \Urlslab_Vendor\GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-URLSLAB-KEY');
        if ($apiKey !== null) {
            $headers['X-URLSLAB-KEY'] = $apiKey;
        }
        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        $headers = \array_merge($defaultHeaders, $headerParams, $headers);
        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request('GET', $operationHost . $resourcePath . ($query ? "?{$query}" : ''), $headers, $httpBody);
    }
    /**
     * Operation loadOriginalImage
     *
     * Fetching fullpage screenshot of url
     *
     * @param  string $bucket_id bucket_id (required)
     * @param  string $body API Key to be validated (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loadOriginalImage'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \SplFileObject
     */
    public function loadOriginalImage($bucket_id, $body = null, string $contentType = self::contentTypes['loadOriginalImage'][0])
    {
        list($response) = $this->loadOriginalImageWithHttpInfo($bucket_id, $body, $contentType);
        return $response;
    }
    /**
     * Operation loadOriginalImageWithHttpInfo
     *
     * Fetching fullpage screenshot of url
     *
     * @param  string $bucket_id (required)
     * @param  string $body API Key to be validated (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loadOriginalImage'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \SplFileObject, HTTP status code, HTTP response headers (array of strings)
     */
    public function loadOriginalImageWithHttpInfo($bucket_id, $body = null, string $contentType = self::contentTypes['loadOriginalImage'][0])
    {
        $request = $this->loadOriginalImageRequest($bucket_id, $body, $contentType);
        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), $e->getResponse() ? $e->getResponse()->getHeaders() : null, $e->getResponse() ? (string) $e->getResponse()->getBody() : null);
            } catch (ConnectException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), null, null);
            }
            $statusCode = $response->getStatusCode();
            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(\sprintf('[%d] Error connecting to the API (%s)', $statusCode, (string) $request->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
            }
            switch ($statusCode) {
                case 200:
                    if ('\\SplFileObject' === '\\SplFileObject') {
                        $content = $response->getBody();
                        //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\\SplFileObject' !== 'string') {
                            $content = \json_decode($content);
                        }
                    }
                    return [ObjectSerializer::deserialize($content, '\\SplFileObject', []), $response->getStatusCode(), $response->getHeaders()];
            }
            $returnType = '\\SplFileObject';
            if ($returnType === '\\SplFileObject') {
                $content = $response->getBody();
                //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = \json_decode($content);
                }
            }
            return [ObjectSerializer::deserialize($content, $returnType, []), $response->getStatusCode(), $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\\SplFileObject', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }
    /**
     * Operation loadOriginalImageAsync
     *
     * Fetching fullpage screenshot of url
     *
     * @param  string $bucket_id (required)
     * @param  string $body API Key to be validated (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loadOriginalImage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function loadOriginalImageAsync($bucket_id, $body = null, string $contentType = self::contentTypes['loadOriginalImage'][0])
    {
        return $this->loadOriginalImageAsyncWithHttpInfo($bucket_id, $body, $contentType)->then(function ($response) {
            return $response[0];
        });
    }
    /**
     * Operation loadOriginalImageAsyncWithHttpInfo
     *
     * Fetching fullpage screenshot of url
     *
     * @param  string $bucket_id (required)
     * @param  string $body API Key to be validated (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loadOriginalImage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function loadOriginalImageAsyncWithHttpInfo($bucket_id, $body = null, string $contentType = self::contentTypes['loadOriginalImage'][0])
    {
        $returnType = '\\SplFileObject';
        $request = $this->loadOriginalImageRequest($bucket_id, $body, $contentType);
        return $this->client->sendAsync($request, $this->createHttpClientOption())->then(function ($response) use($returnType) {
            if ($returnType === '\\SplFileObject') {
                $content = $response->getBody();
                //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = \json_decode($content);
                }
            }
            return [ObjectSerializer::deserialize($content, $returnType, []), $response->getStatusCode(), $response->getHeaders()];
        }, function ($exception) {
            $response = $exception->getResponse();
            $statusCode = $response->getStatusCode();
            throw new ApiException(\sprintf('[%d] Error connecting to the API (%s)', $statusCode, $exception->getRequest()->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
        });
    }
    /**
     * Create request for operation 'loadOriginalImage'
     *
     * @param  string $bucket_id (required)
     * @param  string $body API Key to be validated (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loadOriginalImage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function loadOriginalImageRequest($bucket_id, $body = null, string $contentType = self::contentTypes['loadOriginalImage'][0])
    {
        // verify the required parameter 'bucket_id' is set
        if ($bucket_id === null || \is_array($bucket_id) && \count($bucket_id) === 0) {
            throw new \InvalidArgumentException('Missing the required parameter $bucket_id when calling loadOriginalImage');
        }
        $resourcePath = '/v1/public/screenshot/fullpage/{bucketId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = \false;
        // path params
        if ($bucket_id !== null) {
            $resourcePath = \str_replace('{' . 'bucketId' . '}', ObjectSerializer::toPathValue($bucket_id), $resourcePath);
        }
        $headers = $this->headerSelector->selectHeaders(['image/png'], $contentType, $multipart);
        // for model (json/xml)
        if (isset($body)) {
            if (\stripos($headers['Content-Type'], 'application/json') !== \false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \Urlslab_Vendor\GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($body));
            } else {
                $httpBody = $body;
            }
        } elseif (\count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = \is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = ['name' => $formParamName, 'contents' => $formParamValueItem];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (\stripos($headers['Content-Type'], 'application/json') !== \false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \Urlslab_Vendor\GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-URLSLAB-KEY');
        if ($apiKey !== null) {
            $headers['X-URLSLAB-KEY'] = $apiKey;
        }
        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        $headers = \array_merge($defaultHeaders, $headerParams, $headers);
        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request('GET', $operationHost . $resourcePath . ($query ? "?{$query}" : ''), $headers, $httpBody);
    }
    /**
     * Operation loadTechnologyLogo
     *
     * Fetching icon logo of technology
     *
     * @param  string $icon_name icon_name (required)
     * @param  string $body API Key to be validated (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loadTechnologyLogo'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \SplFileObject
     */
    public function loadTechnologyLogo($icon_name, $body = null, string $contentType = self::contentTypes['loadTechnologyLogo'][0])
    {
        list($response) = $this->loadTechnologyLogoWithHttpInfo($icon_name, $body, $contentType);
        return $response;
    }
    /**
     * Operation loadTechnologyLogoWithHttpInfo
     *
     * Fetching icon logo of technology
     *
     * @param  string $icon_name (required)
     * @param  string $body API Key to be validated (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loadTechnologyLogo'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \SplFileObject, HTTP status code, HTTP response headers (array of strings)
     */
    public function loadTechnologyLogoWithHttpInfo($icon_name, $body = null, string $contentType = self::contentTypes['loadTechnologyLogo'][0])
    {
        $request = $this->loadTechnologyLogoRequest($icon_name, $body, $contentType);
        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), $e->getResponse() ? $e->getResponse()->getHeaders() : null, $e->getResponse() ? (string) $e->getResponse()->getBody() : null);
            } catch (ConnectException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), null, null);
            }
            $statusCode = $response->getStatusCode();
            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(\sprintf('[%d] Error connecting to the API (%s)', $statusCode, (string) $request->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
            }
            switch ($statusCode) {
                case 200:
                    if ('\\SplFileObject' === '\\SplFileObject') {
                        $content = $response->getBody();
                        //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\\SplFileObject' !== 'string') {
                            $content = \json_decode($content);
                        }
                    }
                    return [ObjectSerializer::deserialize($content, '\\SplFileObject', []), $response->getStatusCode(), $response->getHeaders()];
            }
            $returnType = '\\SplFileObject';
            if ($returnType === '\\SplFileObject') {
                $content = $response->getBody();
                //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = \json_decode($content);
                }
            }
            return [ObjectSerializer::deserialize($content, $returnType, []), $response->getStatusCode(), $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\\SplFileObject', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }
    /**
     * Operation loadTechnologyLogoAsync
     *
     * Fetching icon logo of technology
     *
     * @param  string $icon_name (required)
     * @param  string $body API Key to be validated (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loadTechnologyLogo'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function loadTechnologyLogoAsync($icon_name, $body = null, string $contentType = self::contentTypes['loadTechnologyLogo'][0])
    {
        return $this->loadTechnologyLogoAsyncWithHttpInfo($icon_name, $body, $contentType)->then(function ($response) {
            return $response[0];
        });
    }
    /**
     * Operation loadTechnologyLogoAsyncWithHttpInfo
     *
     * Fetching icon logo of technology
     *
     * @param  string $icon_name (required)
     * @param  string $body API Key to be validated (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loadTechnologyLogo'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function loadTechnologyLogoAsyncWithHttpInfo($icon_name, $body = null, string $contentType = self::contentTypes['loadTechnologyLogo'][0])
    {
        $returnType = '\\SplFileObject';
        $request = $this->loadTechnologyLogoRequest($icon_name, $body, $contentType);
        return $this->client->sendAsync($request, $this->createHttpClientOption())->then(function ($response) use($returnType) {
            if ($returnType === '\\SplFileObject') {
                $content = $response->getBody();
                //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = \json_decode($content);
                }
            }
            return [ObjectSerializer::deserialize($content, $returnType, []), $response->getStatusCode(), $response->getHeaders()];
        }, function ($exception) {
            $response = $exception->getResponse();
            $statusCode = $response->getStatusCode();
            throw new ApiException(\sprintf('[%d] Error connecting to the API (%s)', $statusCode, $exception->getRequest()->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
        });
    }
    /**
     * Create request for operation 'loadTechnologyLogo'
     *
     * @param  string $icon_name (required)
     * @param  string $body API Key to be validated (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loadTechnologyLogo'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function loadTechnologyLogoRequest($icon_name, $body = null, string $contentType = self::contentTypes['loadTechnologyLogo'][0])
    {
        // verify the required parameter 'icon_name' is set
        if ($icon_name === null || \is_array($icon_name) && \count($icon_name) === 0) {
            throw new \InvalidArgumentException('Missing the required parameter $icon_name when calling loadTechnologyLogo');
        }
        $resourcePath = '/v1/public/technologies/logos/{iconName}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = \false;
        // path params
        if ($icon_name !== null) {
            $resourcePath = \str_replace('{' . 'iconName' . '}', ObjectSerializer::toPathValue($icon_name), $resourcePath);
        }
        $headers = $this->headerSelector->selectHeaders(['image/png'], $contentType, $multipart);
        // for model (json/xml)
        if (isset($body)) {
            if (\stripos($headers['Content-Type'], 'application/json') !== \false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \Urlslab_Vendor\GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($body));
            } else {
                $httpBody = $body;
            }
        } elseif (\count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = \is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = ['name' => $formParamName, 'contents' => $formParamValueItem];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (\stripos($headers['Content-Type'], 'application/json') !== \false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \Urlslab_Vendor\GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-URLSLAB-KEY');
        if ($apiKey !== null) {
            $headers['X-URLSLAB-KEY'] = $apiKey;
        }
        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        $headers = \array_merge($defaultHeaders, $headerParams, $headers);
        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request('GET', $operationHost . $resourcePath . ($query ? "?{$query}" : ''), $headers, $httpBody);
    }
    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = \fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }
        return $options;
    }
}
