<?php

/**
 * ScheduleApi
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
/**
 * URLSLAB API
 *
 * optimize your website with SEO
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
namespace Urlslab_Vendor\OpenAPI\Client\Urlslab;

use Urlslab_Vendor\GuzzleHttp\Client;
use Urlslab_Vendor\GuzzleHttp\ClientInterface;
use Urlslab_Vendor\GuzzleHttp\Exception\ConnectException;
use Urlslab_Vendor\GuzzleHttp\Exception\RequestException;
use Urlslab_Vendor\GuzzleHttp\Psr7\MultipartStream;
use Urlslab_Vendor\GuzzleHttp\Psr7\Request;
use Urlslab_Vendor\GuzzleHttp\RequestOptions;
use Urlslab_Vendor\OpenAPI\Client\ApiException;
use Urlslab_Vendor\OpenAPI\Client\Configuration;
use Urlslab_Vendor\OpenAPI\Client\HeaderSelector;
use Urlslab_Vendor\OpenAPI\Client\ObjectSerializer;
/**
 * ScheduleApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ScheduleApi
{
    /**
     * @var ClientInterface
     */
    protected $client;
    /**
     * @var Configuration
     */
    protected $config;
    /**
     * @var HeaderSelector
     */
    protected $headerSelector;
    /**
     * @var int Host index
     */
    protected $hostIndex;
    /** @var string[] $contentTypes **/
    public const contentTypes = ['createSchedule' => ['application/json'], 'deleteSchedule' => ['text/plain'], 'getSchedule' => ['text/plain'], 'listSchedules' => ['text/plain']];
    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(ClientInterface $client = null, Configuration $config = null, HeaderSelector $selector = null, $hostIndex = 0)
    {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }
    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex) : void
    {
        $this->hostIndex = $hostIndex;
    }
    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }
    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }
    /**
     * Operation createSchedule
     *
     * create a new schedule
     *
     * @param  \OpenAPI\Client\Model\DomainScheduleScheduleConf $domain_schedule_schedule_conf domain_schedule_schedule_conf (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createSchedule'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\DomainScheduleAPISchedule[]
     */
    public function createSchedule($domain_schedule_schedule_conf = null, string $contentType = self::contentTypes['createSchedule'][0])
    {
        list($response) = $this->createScheduleWithHttpInfo($domain_schedule_schedule_conf, $contentType);
        return $response;
    }
    /**
     * Operation createScheduleWithHttpInfo
     *
     * create a new schedule
     *
     * @param  \OpenAPI\Client\Model\DomainScheduleScheduleConf $domain_schedule_schedule_conf (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createSchedule'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\DomainScheduleAPISchedule[], HTTP status code, HTTP response headers (array of strings)
     */
    public function createScheduleWithHttpInfo($domain_schedule_schedule_conf = null, string $contentType = self::contentTypes['createSchedule'][0])
    {
        $request = $this->createScheduleRequest($domain_schedule_schedule_conf, $contentType);
        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), $e->getResponse() ? $e->getResponse()->getHeaders() : null, $e->getResponse() ? (string) $e->getResponse()->getBody() : null);
            } catch (ConnectException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), null, null);
            }
            $statusCode = $response->getStatusCode();
            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(\sprintf('[%d] Error connecting to the API (%s)', $statusCode, (string) $request->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
            }
            switch ($statusCode) {
                case 200:
                    if ('\\OpenAPI\\Client\\Model\\DomainScheduleAPISchedule[]' === '\\SplFileObject') {
                        $content = $response->getBody();
                        //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\\OpenAPI\\Client\\Model\\DomainScheduleAPISchedule[]' !== 'string') {
                            $content = \json_decode($content);
                        }
                    }
                    return [ObjectSerializer::deserialize($content, '\\OpenAPI\\Client\\Model\\DomainScheduleAPISchedule[]', []), $response->getStatusCode(), $response->getHeaders()];
            }
            $returnType = '\\OpenAPI\\Client\\Model\\DomainScheduleAPISchedule[]';
            if ($returnType === '\\SplFileObject') {
                $content = $response->getBody();
                //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = \json_decode($content);
                }
            }
            return [ObjectSerializer::deserialize($content, $returnType, []), $response->getStatusCode(), $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\\OpenAPI\\Client\\Model\\DomainScheduleAPISchedule[]', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }
    /**
     * Operation createScheduleAsync
     *
     * create a new schedule
     *
     * @param  \OpenAPI\Client\Model\DomainScheduleScheduleConf $domain_schedule_schedule_conf (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createSchedule'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createScheduleAsync($domain_schedule_schedule_conf = null, string $contentType = self::contentTypes['createSchedule'][0])
    {
        return $this->createScheduleAsyncWithHttpInfo($domain_schedule_schedule_conf, $contentType)->then(function ($response) {
            return $response[0];
        });
    }
    /**
     * Operation createScheduleAsyncWithHttpInfo
     *
     * create a new schedule
     *
     * @param  \OpenAPI\Client\Model\DomainScheduleScheduleConf $domain_schedule_schedule_conf (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createSchedule'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createScheduleAsyncWithHttpInfo($domain_schedule_schedule_conf = null, string $contentType = self::contentTypes['createSchedule'][0])
    {
        $returnType = '\\OpenAPI\\Client\\Model\\DomainScheduleAPISchedule[]';
        $request = $this->createScheduleRequest($domain_schedule_schedule_conf, $contentType);
        return $this->client->sendAsync($request, $this->createHttpClientOption())->then(function ($response) use($returnType) {
            if ($returnType === '\\SplFileObject') {
                $content = $response->getBody();
                //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = \json_decode($content);
                }
            }
            return [ObjectSerializer::deserialize($content, $returnType, []), $response->getStatusCode(), $response->getHeaders()];
        }, function ($exception) {
            $response = $exception->getResponse();
            $statusCode = $response->getStatusCode();
            throw new ApiException(\sprintf('[%d] Error connecting to the API (%s)', $statusCode, $exception->getRequest()->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
        });
    }
    /**
     * Create request for operation 'createSchedule'
     *
     * @param  \OpenAPI\Client\Model\DomainScheduleScheduleConf $domain_schedule_schedule_conf (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createSchedule'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createScheduleRequest($domain_schedule_schedule_conf = null, string $contentType = self::contentTypes['createSchedule'][0])
    {
        $resourcePath = '/v1/schedule';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = \false;
        $headers = $this->headerSelector->selectHeaders(['application/json'], $contentType, $multipart);
        // for model (json/xml)
        if (isset($domain_schedule_schedule_conf)) {
            if (\stripos($headers['Content-Type'], 'application/json') !== \false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \Urlslab_Vendor\GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($domain_schedule_schedule_conf));
            } else {
                $httpBody = $domain_schedule_schedule_conf;
            }
        } elseif (\count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = \is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = ['name' => $formParamName, 'contents' => $formParamValueItem];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (\stripos($headers['Content-Type'], 'application/json') !== \false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \Urlslab_Vendor\GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-URLSLAB-KEY');
        if ($apiKey !== null) {
            $headers['X-URLSLAB-KEY'] = $apiKey;
        }
        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        $headers = \array_merge($defaultHeaders, $headerParams, $headers);
        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request('PUT', $operationHost . $resourcePath . ($query ? "?{$query}" : ''), $headers, $httpBody);
    }
    /**
     * Operation deleteSchedule
     *
     * delete a schedule
     *
     * @param  string $id id (required)
     * @param  string $body API Key to be validated (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteSchedule'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\DomainAcknowledged
     */
    public function deleteSchedule($id, $body = null, string $contentType = self::contentTypes['deleteSchedule'][0])
    {
        list($response) = $this->deleteScheduleWithHttpInfo($id, $body, $contentType);
        return $response;
    }
    /**
     * Operation deleteScheduleWithHttpInfo
     *
     * delete a schedule
     *
     * @param  string $id (required)
     * @param  string $body API Key to be validated (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteSchedule'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\DomainAcknowledged, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteScheduleWithHttpInfo($id, $body = null, string $contentType = self::contentTypes['deleteSchedule'][0])
    {
        $request = $this->deleteScheduleRequest($id, $body, $contentType);
        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), $e->getResponse() ? $e->getResponse()->getHeaders() : null, $e->getResponse() ? (string) $e->getResponse()->getBody() : null);
            } catch (ConnectException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), null, null);
            }
            $statusCode = $response->getStatusCode();
            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(\sprintf('[%d] Error connecting to the API (%s)', $statusCode, (string) $request->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
            }
            switch ($statusCode) {
                case 200:
                    if ('\\OpenAPI\\Client\\Model\\DomainAcknowledged' === '\\SplFileObject') {
                        $content = $response->getBody();
                        //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\\OpenAPI\\Client\\Model\\DomainAcknowledged' !== 'string') {
                            $content = \json_decode($content);
                        }
                    }
                    return [ObjectSerializer::deserialize($content, 'Urlslab_Vendor\\OpenAPI\\Client\\Model\\DomainAcknowledged', []), $response->getStatusCode(), $response->getHeaders()];
            }
            $returnType = 'Urlslab_Vendor\\OpenAPI\\Client\\Model\\DomainAcknowledged';
            if ($returnType === '\\SplFileObject') {
                $content = $response->getBody();
                //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = \json_decode($content);
                }
            }
            return [ObjectSerializer::deserialize($content, $returnType, []), $response->getStatusCode(), $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), 'Urlslab_Vendor\\OpenAPI\\Client\\Model\\DomainAcknowledged', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }
    /**
     * Operation deleteScheduleAsync
     *
     * delete a schedule
     *
     * @param  string $id (required)
     * @param  string $body API Key to be validated (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteSchedule'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteScheduleAsync($id, $body = null, string $contentType = self::contentTypes['deleteSchedule'][0])
    {
        return $this->deleteScheduleAsyncWithHttpInfo($id, $body, $contentType)->then(function ($response) {
            return $response[0];
        });
    }
    /**
     * Operation deleteScheduleAsyncWithHttpInfo
     *
     * delete a schedule
     *
     * @param  string $id (required)
     * @param  string $body API Key to be validated (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteSchedule'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteScheduleAsyncWithHttpInfo($id, $body = null, string $contentType = self::contentTypes['deleteSchedule'][0])
    {
        $returnType = 'Urlslab_Vendor\\OpenAPI\\Client\\Model\\DomainAcknowledged';
        $request = $this->deleteScheduleRequest($id, $body, $contentType);
        return $this->client->sendAsync($request, $this->createHttpClientOption())->then(function ($response) use($returnType) {
            if ($returnType === '\\SplFileObject') {
                $content = $response->getBody();
                //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = \json_decode($content);
                }
            }
            return [ObjectSerializer::deserialize($content, $returnType, []), $response->getStatusCode(), $response->getHeaders()];
        }, function ($exception) {
            $response = $exception->getResponse();
            $statusCode = $response->getStatusCode();
            throw new ApiException(\sprintf('[%d] Error connecting to the API (%s)', $statusCode, $exception->getRequest()->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
        });
    }
    /**
     * Create request for operation 'deleteSchedule'
     *
     * @param  string $id (required)
     * @param  string $body API Key to be validated (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteSchedule'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deleteScheduleRequest($id, $body = null, string $contentType = self::contentTypes['deleteSchedule'][0])
    {
        // verify the required parameter 'id' is set
        if ($id === null || \is_array($id) && \count($id) === 0) {
            throw new \InvalidArgumentException('Missing the required parameter $id when calling deleteSchedule');
        }
        $resourcePath = '/v1/schedule/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = \false;
        // path params
        if ($id !== null) {
            $resourcePath = \str_replace('{' . 'id' . '}', ObjectSerializer::toPathValue($id), $resourcePath);
        }
        $headers = $this->headerSelector->selectHeaders(['application/json'], $contentType, $multipart);
        // for model (json/xml)
        if (isset($body)) {
            if (\stripos($headers['Content-Type'], 'application/json') !== \false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \Urlslab_Vendor\GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($body));
            } else {
                $httpBody = $body;
            }
        } elseif (\count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = \is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = ['name' => $formParamName, 'contents' => $formParamValueItem];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (\stripos($headers['Content-Type'], 'application/json') !== \false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \Urlslab_Vendor\GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-URLSLAB-KEY');
        if ($apiKey !== null) {
            $headers['X-URLSLAB-KEY'] = $apiKey;
        }
        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        $headers = \array_merge($defaultHeaders, $headerParams, $headers);
        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request('DELETE', $operationHost . $resourcePath . ($query ? "?{$query}" : ''), $headers, $httpBody);
    }
    /**
     * Operation getSchedule
     *
     * get a specific schedule details
     *
     * @param  string $id id (required)
     * @param  string $body API Key to be validated (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSchedule'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\DomainScheduleAPISchedule
     */
    public function getSchedule($id, $body = null, string $contentType = self::contentTypes['getSchedule'][0])
    {
        list($response) = $this->getScheduleWithHttpInfo($id, $body, $contentType);
        return $response;
    }
    /**
     * Operation getScheduleWithHttpInfo
     *
     * get a specific schedule details
     *
     * @param  string $id (required)
     * @param  string $body API Key to be validated (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSchedule'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\DomainScheduleAPISchedule, HTTP status code, HTTP response headers (array of strings)
     */
    public function getScheduleWithHttpInfo($id, $body = null, string $contentType = self::contentTypes['getSchedule'][0])
    {
        $request = $this->getScheduleRequest($id, $body, $contentType);
        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), $e->getResponse() ? $e->getResponse()->getHeaders() : null, $e->getResponse() ? (string) $e->getResponse()->getBody() : null);
            } catch (ConnectException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), null, null);
            }
            $statusCode = $response->getStatusCode();
            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(\sprintf('[%d] Error connecting to the API (%s)', $statusCode, (string) $request->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
            }
            switch ($statusCode) {
                case 200:
                    if ('\\OpenAPI\\Client\\Model\\DomainScheduleAPISchedule' === '\\SplFileObject') {
                        $content = $response->getBody();
                        //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\\OpenAPI\\Client\\Model\\DomainScheduleAPISchedule' !== 'string') {
                            $content = \json_decode($content);
                        }
                    }
                    return [ObjectSerializer::deserialize($content, 'Urlslab_Vendor\\OpenAPI\\Client\\Model\\DomainScheduleAPISchedule', []), $response->getStatusCode(), $response->getHeaders()];
            }
            $returnType = 'Urlslab_Vendor\\OpenAPI\\Client\\Model\\DomainScheduleAPISchedule';
            if ($returnType === '\\SplFileObject') {
                $content = $response->getBody();
                //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = \json_decode($content);
                }
            }
            return [ObjectSerializer::deserialize($content, $returnType, []), $response->getStatusCode(), $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), 'Urlslab_Vendor\\OpenAPI\\Client\\Model\\DomainScheduleAPISchedule', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }
    /**
     * Operation getScheduleAsync
     *
     * get a specific schedule details
     *
     * @param  string $id (required)
     * @param  string $body API Key to be validated (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSchedule'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getScheduleAsync($id, $body = null, string $contentType = self::contentTypes['getSchedule'][0])
    {
        return $this->getScheduleAsyncWithHttpInfo($id, $body, $contentType)->then(function ($response) {
            return $response[0];
        });
    }
    /**
     * Operation getScheduleAsyncWithHttpInfo
     *
     * get a specific schedule details
     *
     * @param  string $id (required)
     * @param  string $body API Key to be validated (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSchedule'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getScheduleAsyncWithHttpInfo($id, $body = null, string $contentType = self::contentTypes['getSchedule'][0])
    {
        $returnType = 'Urlslab_Vendor\\OpenAPI\\Client\\Model\\DomainScheduleAPISchedule';
        $request = $this->getScheduleRequest($id, $body, $contentType);
        return $this->client->sendAsync($request, $this->createHttpClientOption())->then(function ($response) use($returnType) {
            if ($returnType === '\\SplFileObject') {
                $content = $response->getBody();
                //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = \json_decode($content);
                }
            }
            return [ObjectSerializer::deserialize($content, $returnType, []), $response->getStatusCode(), $response->getHeaders()];
        }, function ($exception) {
            $response = $exception->getResponse();
            $statusCode = $response->getStatusCode();
            throw new ApiException(\sprintf('[%d] Error connecting to the API (%s)', $statusCode, $exception->getRequest()->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
        });
    }
    /**
     * Create request for operation 'getSchedule'
     *
     * @param  string $id (required)
     * @param  string $body API Key to be validated (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSchedule'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getScheduleRequest($id, $body = null, string $contentType = self::contentTypes['getSchedule'][0])
    {
        // verify the required parameter 'id' is set
        if ($id === null || \is_array($id) && \count($id) === 0) {
            throw new \InvalidArgumentException('Missing the required parameter $id when calling getSchedule');
        }
        $resourcePath = '/v1/schedule/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = \false;
        // path params
        if ($id !== null) {
            $resourcePath = \str_replace('{' . 'id' . '}', ObjectSerializer::toPathValue($id), $resourcePath);
        }
        $headers = $this->headerSelector->selectHeaders(['application/json'], $contentType, $multipart);
        // for model (json/xml)
        if (isset($body)) {
            if (\stripos($headers['Content-Type'], 'application/json') !== \false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \Urlslab_Vendor\GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($body));
            } else {
                $httpBody = $body;
            }
        } elseif (\count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = \is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = ['name' => $formParamName, 'contents' => $formParamValueItem];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (\stripos($headers['Content-Type'], 'application/json') !== \false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \Urlslab_Vendor\GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-URLSLAB-KEY');
        if ($apiKey !== null) {
            $headers['X-URLSLAB-KEY'] = $apiKey;
        }
        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        $headers = \array_merge($defaultHeaders, $headerParams, $headers);
        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request('GET', $operationHost . $resourcePath . ($query ? "?{$query}" : ''), $headers, $httpBody);
    }
    /**
     * Operation listSchedules
     *
     * get list of all schedules for the user
     *
     * @param  string $body API Key to be validated (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listSchedules'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\DomainScheduleAPISchedule[]
     */
    public function listSchedules($body = null, string $contentType = self::contentTypes['listSchedules'][0])
    {
        list($response) = $this->listSchedulesWithHttpInfo($body, $contentType);
        return $response;
    }
    /**
     * Operation listSchedulesWithHttpInfo
     *
     * get list of all schedules for the user
     *
     * @param  string $body API Key to be validated (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listSchedules'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\DomainScheduleAPISchedule[], HTTP status code, HTTP response headers (array of strings)
     */
    public function listSchedulesWithHttpInfo($body = null, string $contentType = self::contentTypes['listSchedules'][0])
    {
        $request = $this->listSchedulesRequest($body, $contentType);
        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), $e->getResponse() ? $e->getResponse()->getHeaders() : null, $e->getResponse() ? (string) $e->getResponse()->getBody() : null);
            } catch (ConnectException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), null, null);
            }
            $statusCode = $response->getStatusCode();
            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(\sprintf('[%d] Error connecting to the API (%s)', $statusCode, (string) $request->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
            }
            switch ($statusCode) {
                case 200:
                    if ('\\OpenAPI\\Client\\Model\\DomainScheduleAPISchedule[]' === '\\SplFileObject') {
                        $content = $response->getBody();
                        //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\\OpenAPI\\Client\\Model\\DomainScheduleAPISchedule[]' !== 'string') {
                            $content = \json_decode($content);
                        }
                    }
                    return [ObjectSerializer::deserialize($content, '\\OpenAPI\\Client\\Model\\DomainScheduleAPISchedule[]', []), $response->getStatusCode(), $response->getHeaders()];
            }
            $returnType = '\\OpenAPI\\Client\\Model\\DomainScheduleAPISchedule[]';
            if ($returnType === '\\SplFileObject') {
                $content = $response->getBody();
                //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = \json_decode($content);
                }
            }
            return [ObjectSerializer::deserialize($content, $returnType, []), $response->getStatusCode(), $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\\OpenAPI\\Client\\Model\\DomainScheduleAPISchedule[]', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }
    /**
     * Operation listSchedulesAsync
     *
     * get list of all schedules for the user
     *
     * @param  string $body API Key to be validated (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listSchedules'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listSchedulesAsync($body = null, string $contentType = self::contentTypes['listSchedules'][0])
    {
        return $this->listSchedulesAsyncWithHttpInfo($body, $contentType)->then(function ($response) {
            return $response[0];
        });
    }
    /**
     * Operation listSchedulesAsyncWithHttpInfo
     *
     * get list of all schedules for the user
     *
     * @param  string $body API Key to be validated (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listSchedules'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listSchedulesAsyncWithHttpInfo($body = null, string $contentType = self::contentTypes['listSchedules'][0])
    {
        $returnType = '\\OpenAPI\\Client\\Model\\DomainScheduleAPISchedule[]';
        $request = $this->listSchedulesRequest($body, $contentType);
        return $this->client->sendAsync($request, $this->createHttpClientOption())->then(function ($response) use($returnType) {
            if ($returnType === '\\SplFileObject') {
                $content = $response->getBody();
                //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = \json_decode($content);
                }
            }
            return [ObjectSerializer::deserialize($content, $returnType, []), $response->getStatusCode(), $response->getHeaders()];
        }, function ($exception) {
            $response = $exception->getResponse();
            $statusCode = $response->getStatusCode();
            throw new ApiException(\sprintf('[%d] Error connecting to the API (%s)', $statusCode, $exception->getRequest()->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
        });
    }
    /**
     * Create request for operation 'listSchedules'
     *
     * @param  string $body API Key to be validated (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listSchedules'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listSchedulesRequest($body = null, string $contentType = self::contentTypes['listSchedules'][0])
    {
        $resourcePath = '/v1/schedule';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = \false;
        $headers = $this->headerSelector->selectHeaders(['application/json'], $contentType, $multipart);
        // for model (json/xml)
        if (isset($body)) {
            if (\stripos($headers['Content-Type'], 'application/json') !== \false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \Urlslab_Vendor\GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($body));
            } else {
                $httpBody = $body;
            }
        } elseif (\count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = \is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = ['name' => $formParamName, 'contents' => $formParamValueItem];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (\stripos($headers['Content-Type'], 'application/json') !== \false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \Urlslab_Vendor\GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-URLSLAB-KEY');
        if ($apiKey !== null) {
            $headers['X-URLSLAB-KEY'] = $apiKey;
        }
        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        $headers = \array_merge($defaultHeaders, $headerParams, $headers);
        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request('GET', $operationHost . $resourcePath . ($query ? "?{$query}" : ''), $headers, $httpBody);
    }
    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = \fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }
        return $options;
    }
}
