<?php

/**
 * SummaryApi
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
/**
 * URLSLAB API
 *
 * optimize your website with SEO
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
namespace Urlslab_Vendor\OpenAPI\Client\Urlslab;

use Urlslab_Vendor\GuzzleHttp\Client;
use Urlslab_Vendor\GuzzleHttp\ClientInterface;
use Urlslab_Vendor\GuzzleHttp\Exception\ConnectException;
use Urlslab_Vendor\GuzzleHttp\Exception\RequestException;
use Urlslab_Vendor\GuzzleHttp\Psr7\MultipartStream;
use Urlslab_Vendor\GuzzleHttp\Psr7\Request;
use Urlslab_Vendor\GuzzleHttp\RequestOptions;
use Urlslab_Vendor\OpenAPI\Client\ApiException;
use Urlslab_Vendor\OpenAPI\Client\Configuration;
use Urlslab_Vendor\OpenAPI\Client\HeaderSelector;
use Urlslab_Vendor\OpenAPI\Client\ObjectSerializer;
/**
 * SummaryApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SummaryApi
{
    /**
     * @var ClientInterface
     */
    protected $client;
    /**
     * @var Configuration
     */
    protected $config;
    /**
     * @var HeaderSelector
     */
    protected $headerSelector;
    /**
     * @var int Host index
     */
    protected $hostIndex;
    /** @var string[] $contentTypes **/
    public const contentTypes = ['getSummary' => ['application/json']];
    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(ClientInterface $client = null, Configuration $config = null, HeaderSelector $selector = null, $hostIndex = 0)
    {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }
    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex) : void
    {
        $this->hostIndex = $hostIndex;
    }
    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }
    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }
    /**
     * Operation getSummary
     *
     * Get summarization data for url
     *
     * @param  \OpenAPI\Client\Model\DomainDataRetrievalDataRequest[] $domain_data_retrieval_data_request domain_data_retrieval_data_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSummary'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\DomainDataRetrievalSummaryResponse[]
     */
    public function getSummary($domain_data_retrieval_data_request = null, string $contentType = self::contentTypes['getSummary'][0])
    {
        list($response) = $this->getSummaryWithHttpInfo($domain_data_retrieval_data_request, $contentType);
        return $response;
    }
    /**
     * Operation getSummaryWithHttpInfo
     *
     * Get summarization data for url
     *
     * @param  \OpenAPI\Client\Model\DomainDataRetrievalDataRequest[] $domain_data_retrieval_data_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSummary'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\DomainDataRetrievalSummaryResponse[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getSummaryWithHttpInfo($domain_data_retrieval_data_request = null, string $contentType = self::contentTypes['getSummary'][0])
    {
        $request = $this->getSummaryRequest($domain_data_retrieval_data_request, $contentType);
        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), $e->getResponse() ? $e->getResponse()->getHeaders() : null, $e->getResponse() ? (string) $e->getResponse()->getBody() : null);
            } catch (ConnectException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), null, null);
            }
            $statusCode = $response->getStatusCode();
            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(\sprintf('[%d] Error connecting to the API (%s)', $statusCode, (string) $request->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
            }
            switch ($statusCode) {
                case 200:
                    if ('\\OpenAPI\\Client\\Model\\DomainDataRetrievalSummaryResponse[]' === '\\SplFileObject') {
                        $content = $response->getBody();
                        //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\\OpenAPI\\Client\\Model\\DomainDataRetrievalSummaryResponse[]' !== 'string') {
                            $content = \json_decode($content);
                        }
                    }
                    return [ObjectSerializer::deserialize($content, '\\OpenAPI\\Client\\Model\\DomainDataRetrievalSummaryResponse[]', []), $response->getStatusCode(), $response->getHeaders()];
            }
            $returnType = '\\OpenAPI\\Client\\Model\\DomainDataRetrievalSummaryResponse[]';
            if ($returnType === '\\SplFileObject') {
                $content = $response->getBody();
                //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = \json_decode($content);
                }
            }
            return [ObjectSerializer::deserialize($content, $returnType, []), $response->getStatusCode(), $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\\OpenAPI\\Client\\Model\\DomainDataRetrievalSummaryResponse[]', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }
    /**
     * Operation getSummaryAsync
     *
     * Get summarization data for url
     *
     * @param  \OpenAPI\Client\Model\DomainDataRetrievalDataRequest[] $domain_data_retrieval_data_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSummary'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSummaryAsync($domain_data_retrieval_data_request = null, string $contentType = self::contentTypes['getSummary'][0])
    {
        return $this->getSummaryAsyncWithHttpInfo($domain_data_retrieval_data_request, $contentType)->then(function ($response) {
            return $response[0];
        });
    }
    /**
     * Operation getSummaryAsyncWithHttpInfo
     *
     * Get summarization data for url
     *
     * @param  \OpenAPI\Client\Model\DomainDataRetrievalDataRequest[] $domain_data_retrieval_data_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSummary'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSummaryAsyncWithHttpInfo($domain_data_retrieval_data_request = null, string $contentType = self::contentTypes['getSummary'][0])
    {
        $returnType = '\\OpenAPI\\Client\\Model\\DomainDataRetrievalSummaryResponse[]';
        $request = $this->getSummaryRequest($domain_data_retrieval_data_request, $contentType);
        return $this->client->sendAsync($request, $this->createHttpClientOption())->then(function ($response) use($returnType) {
            if ($returnType === '\\SplFileObject') {
                $content = $response->getBody();
                //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = \json_decode($content);
                }
            }
            return [ObjectSerializer::deserialize($content, $returnType, []), $response->getStatusCode(), $response->getHeaders()];
        }, function ($exception) {
            $response = $exception->getResponse();
            $statusCode = $response->getStatusCode();
            throw new ApiException(\sprintf('[%d] Error connecting to the API (%s)', $statusCode, $exception->getRequest()->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
        });
    }
    /**
     * Create request for operation 'getSummary'
     *
     * @param  \OpenAPI\Client\Model\DomainDataRetrievalDataRequest[] $domain_data_retrieval_data_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSummary'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getSummaryRequest($domain_data_retrieval_data_request = null, string $contentType = self::contentTypes['getSummary'][0])
    {
        $resourcePath = '/v1/summary';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = \false;
        $headers = $this->headerSelector->selectHeaders(['application/json'], $contentType, $multipart);
        // for model (json/xml)
        if (isset($domain_data_retrieval_data_request)) {
            if (\stripos($headers['Content-Type'], 'application/json') !== \false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \Urlslab_Vendor\GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($domain_data_retrieval_data_request));
            } else {
                $httpBody = $domain_data_retrieval_data_request;
            }
        } elseif (\count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = \is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = ['name' => $formParamName, 'contents' => $formParamValueItem];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (\stripos($headers['Content-Type'], 'application/json') !== \false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \Urlslab_Vendor\GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-URLSLAB-KEY');
        if ($apiKey !== null) {
            $headers['X-URLSLAB-KEY'] = $apiKey;
        }
        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        $headers = \array_merge($defaultHeaders, $headerParams, $headers);
        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request('POST', $operationHost . $resourcePath . ($query ? "?{$query}" : ''), $headers, $httpBody);
    }
    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = \fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }
        return $options;
    }
}
