<?php

/**
 * DomainDocsDocResponseTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
/**
 * URLSLAB API
 *
 * optimize your website with SEO
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */
namespace Urlslab_Vendor\OpenAPI\Client\Test\Model;

use Urlslab_Vendor\PHPUnit\Framework\TestCase;
/**
 * DomainDocsDocResponseTest Class Doc Comment
 *
 * @category    Class
 * @description DomainDocsDocResponse
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class DomainDocsDocResponseTest extends TestCase
{
    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass() : void
    {
    }
    /**
     * Setup before running each test case
     */
    public function setUp() : void
    {
    }
    /**
     * Clean up after running each test case
     */
    public function tearDown() : void
    {
    }
    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass() : void
    {
    }
    /**
     * Test "DomainDocsDocResponse"
     */
    public function testDomainDocsDocResponse()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
    /**
     * Test attribute "documents"
     */
    public function testPropertyDocuments()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
    /**
     * Test attribute "count"
     */
    public function testPropertyCount()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
