name: Add PR to the Project

on:
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    name: Add PR to the Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.0.4
        with:
          project-url: https://github.com/orgs/QualityUnit/projects/25
          github-token: ${{ secrets.GH_PAT }}
