# https://github.com/marketplace/actions/auto-assign-action

name: "Auto Assign and Request Review"
on:
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.5
