# Inspired by Elementor Releasing Pipeline https://github.com/elementor/elementor
name: Publish Release Version

# Environmental Variables: WEB_CICD_PAT (PAT), WEB_CICD_USERNAME (GitHub Bot Username), WEB_CICD_MAIL (GitHub Bot E-mail)
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release Type"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
      deploy:
        description: "Deploy Directly to Our Websites"
        required: true
        type: boolean
        default: 'false'
      declare:
        description: "I have updated the changelog in the readme.txt (otherwise, it will fail)"
        required: true
        type: boolean
        default: 'false'


jobs:
  bump-and-publish:
    name: Bump Version and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WEB_CICD_PAT }}
          ref: main

      - name: Setup PHP 8.0
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "yarn"

      - name: Setup YQ
        uses: chrisdickinson/setup-yq@latest
        with:
          yq-version: 'v4.25.2'

      - name: Get Old Version
        id: get_old_version
        run: |
          npm config set git-tag-version false
          PREV_PACKAGE_VERSION=$(node -p "require('./package.json').version")
          echo "PREV_PACKAGE_VERSION=${PREV_PACKAGE_VERSION}" >> $GITHUB_ENV

      - name: Bump Major Version
        if: "${{ github.event.inputs.version == 'major' }}"
        run: npm version major

      - name: Bump Minor Version
        if: "${{ github.event.inputs.version == 'minor' }}"
        run: npm version minor

      - name: Bump Patch Version
        if: "${{ github.event.inputs.version == 'patch' }}"
        run: npm version patch

      - name: Set New Version
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> $GITHUB_ENV

      - name: Get Current Date
        id: get_current_date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S')"

      - name: Get Changelog
        env:
          VERSION: ${{ env.PACKAGE_VERSION }}
        run: |
          yarn
          node ./.github/scripts/get-changelog.js

      - name: Change info.json File
        run: |
          yq -i e -o=json '.version = "${{ env.PACKAGE_VERSION }}"' 'info.json'
          yq -i e -o=json '.download_url = "https://github.com/QualityUnit/wp-urlslab/releases/download/${{ env.PACKAGE_VERSION }}/urlslab-${{ env.PACKAGE_VERSION }}.zip"' 'info.json'
          yq -i e -o=json '.last_updated = "${{ steps.get_current_date.outputs.date }}"' 'info.json'
          yq -i e -o=json '.sections.changelog = load_str("./temp-changelog-from-readme.txt")' 'info.json'
          rm -rf ./temp-changelog-from-readme.txt

      - name: Push New Version with Build Files
        env:
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
          WEB_CICD_MAIL: ${{ secrets.WEB_CICD_MAIL }}
          WEB_CICD_USERNAME: ${{ secrets.WEB_CICD_USERNAME }}
        run: |
          bash "${GITHUB_WORKSPACE}/.github/scripts/update-version-files.sh"
          bash "${GITHUB_WORKSPACE}/.github/scripts/build-files.sh"
          bash "${GITHUB_WORKSPACE}/.github/scripts/commit-push-bump.sh"

      - name: Get Current Version
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> $GITHUB_ENV

      - name: Create Tag
        env:
          WEB_CICD_MAIL: ${{ secrets.WEB_CICD_MAIL }}
          WEB_CICD_USERNAME: ${{ secrets.WEB_CICD_USERNAME }}
        run: |
          bash "${GITHUB_WORKSPACE}/.github/scripts/create-git-tag.sh"

      - name: Install Dependencies
        run: |
          yarn
          cd ./admin/ && yarn

      - name: Update readme.txt File
        run: |
          bash "${GITHUB_WORKSPACE}/.github/scripts/update-readme-stable-version.sh"

      - name: Check if readme.txt Update
        env:
          VERSION: ${{ env.PACKAGE_VERSION }}
        run: |
          node ./.github/scripts/get-changelog-from-readme-txt.js

      - name: Create ZIP File
        env:
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
        run: |
          bash "${GITHUB_WORKSPACE}/.github/scripts/build-zip.sh"

      - name: Upload ZIP File to GitHub Actions Artifact
        uses: actions/upload-artifact@v3
        with:
          name: urlslab-${{ env.PACKAGE_VERSION }}
          path: ${{ github.workspace }}/**/*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.PACKAGE_VERSION }}
          files: urlslab-*.zip
          body_path: temp-changelog-from-readme.txt
        env:
          GITHUB_TOKEN: ${{ secrets.WEB_CICD_PAT }}

  deploy:
    name: Deploy
    needs: bump-and-publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WEB_CICD_PAT }}
          ref: main

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "yarn"

      - name: Get Current Version
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> $GITHUB_ENV

      - name: Trigger the Update Pipeline [LiveAgent]
        if: "${{ github.event.inputs.deploy == 'true' }}"
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: update-urlslab.yml
          repo: QualityUnit/liveagent-wp
          ref: dev
          token: ${{ secrets.WEB_CICD_PAT }}
          wait-for-completion-interval: 5s
          inputs: '{
                  "repository":"liveagent-wp",
                  "version":"${{ env.PACKAGE_VERSION }}"
                }'

      - name: Trigger the Update Pipeline [PostAffiliatePro]
        if: "${{ github.event.inputs.deploy == 'true' }}"
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: update-urlslab.yml
          repo: QualityUnit/postaffiliatepro-wp
          ref: main
          token: ${{ secrets.WEB_CICD_PAT }}
          wait-for-completion-interval: 5s
          inputs: '{
                  "repository":"postaffiliatepro-wp",
                  "version":"${{ env.PACKAGE_VERSION }}"
                }'

      - name: Trigger the Update Pipeline [URLsLab]
        if: "${{ github.event.inputs.deploy == 'true' }}"
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: update-urlslab.yml
          repo: QualityUnit/urlslab-wp
          ref: main
          token: ${{ secrets.WEB_CICD_PAT }}
          wait-for-completion-interval: 5s
          inputs: '{
                  "repository":"urlslab-wp",
                  "version":"${{ env.PACKAGE_VERSION }}"
                }'
