name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]'
      - '[0-9]+.[0-9][0-9]+.[0-9]'
  workflow_call:
    secrets:
      CICD_PAT:
        required: true

jobs:
  build:
    name: 1️⃣ Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup PHP 7.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: 'yarn'

      - name: Install Composer Dependencies
        run: composer install

      - name: Install Yarn dependencies
        run: yarn

      - name: Build CSS and JS
        run: yarn production

      - name: Remove Unnecessary Files
        run: rm -rf .git .idea .github *.md *.lock .editorconfig .eslintignore .eslintrc .gitignore .stylelintrc composer.json *.lock package.json phpcs.xml webpack.config.js commitlint.config.js debug.log

      - name: Get the Version
        id: version
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.ref }}
          regex: ".*/([^/]+)$"

      - name: Create a ZIP File
        run: zip -r urlslab-plugin_${{ steps.version.outputs.group1 }}.zip .

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v0.1.14
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          body: See changes in the [CHANGELOG.md](CHANGELOG.md)
          files: ./urlslab-plugin_${{ steps.version.outputs.group1 }}.zip

  deploy:
    name: 2️⃣ Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Get the Version
        id: version
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.ref }}
          regex: ".*/([^/]+)$"

      - name: Trigger the Update Pipeline [LiveAgent]
        id: trigger-la
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: update-urlslab.yml
          repo: QualityUnit/liveagent-wp
          ref: dev
          token: ${{ secrets.CICD_PAT }}
          wait-for-completion-interval: 5s
          inputs: '{
                  "repository":"liveagent-wp",
                  "version":"${{ steps.version.outputs.group1 }}"
                }'

      - name: Trigger the Update Pipeline [PostAffiliatePro]
        id: trigger-pap
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: update-urlslab.yml
          repo: QualityUnit/postaffiliatepro-wp
          ref: main
          token: ${{ secrets.CICD_PAT }}
          wait-for-completion-interval: 5s
          inputs: '{
                  "repository":"postaffiliatepro-wp",
                  "version":"${{ steps.version.outputs.group1 }}"
                }'
