name: Release Nightly

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-nightly'

jobs:
  build:
    name: 1️⃣ Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup PHP 7.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: 'yarn'

      - name: Install Composer Dependencies
        run: composer install

      - name: Install Yarn dependencies
        run: yarn

      - name: Build CSS and JS
        run: yarn production

      - name: Remove Unnecessary Files
        run: rm -rf .git .idea .github *.md *.lock .editorconfig .eslintignore .eslintrc .gitignore .stylelintrc composer.json *.lock package.json phpcs.xml webpack.config.js commitlint.config.js debug.log

      - name: Get the Version
        id: version
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.ref }}
          regex: ".*/([^/]+)$"

      - name: Create a ZIP File
        run: zip -r urlslab-plugin_${{ steps.version.outputs.group1 }}.zip .

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v0.1.15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: true
          body: See changes in the [CHANGELOG.md](CHANGELOG.md)
          generate_release_notes: true
          append_body: true
          files: ./urlslab-plugin_${{ steps.version.outputs.group1 }}.zip
