<?php

use Urlslab_Vendor\OpenAPI\Client\ApiException;
use Urlslab_Vendor\OpenAPI\Client\Configuration;
use Urlslab_Vendor\OpenAPI\Client\Model\DomainDataRetrievalDataRequest;
use Urlslab_Vendor\OpenAPI\Client\Model\DomainDataRetrievalSummaryResponse;
use Urlslab_Vendor\OpenAPI\Client\Urlslab\SummaryApi;
use Urlslab_Vendor\GuzzleHttp;

require_once URLSLAB_PLUGIN_DIR . '/includes/cron/class-urlslab-cron.php';

class Urlslab_Summaries_Cron extends Urlslab_Cron {
	private SummaryApi $client;

	public function get_description(): string {
		return __( 'Syncing summaries generated by URLsLab service to local database', 'urlslab' );
	}

	protected function execute(): bool {
		if ( ! $this->init_client() ) {
			return false;
		}

		global $wpdb;

		$query_data = array();

		if (
			Urlslab_User_Widget::get_instance()->is_widget_activated( Urlslab_Link_Enhancer::SLUG )
			&& Urlslab_User_Widget::get_instance()->get_widget( Urlslab_Link_Enhancer::SLUG )->get_option( Urlslab_Link_Enhancer::SETTING_NAME_VALIDATE_LINKS )
		) {
			$query_data[]          = Urlslab_Url_Row::HTTP_STATUS_OK;
			$sql_where_http_status = ' http_status = %d AND';
		} else {
			$sql_where_http_status = '';
		}

		$query_data[] = Urlslab_Url_Row::SUM_STATUS_NEW;
		$query_data[] = Urlslab_Url_Row::SUM_STATUS_ACTIVE;
		$query_data[] = Urlslab_Data::get_now( time() - Urlslab_User_Widget::get_instance()->get_widget( Urlslab_General::SLUG )->get_option( Urlslab_General::SETTING_NAME_SUMMARIZATION_REFRESH_INTERVAL ) );
		// PENDING or UPDATING urls will be retried in one hour again
		$query_data[] = Urlslab_Url_Row::SUM_STATUS_PENDING;
		$query_data[] = Urlslab_Data::get_now( time() - 24 * 3600 );

		$url_rows = $wpdb->get_results(
			$wpdb->prepare(
				'SELECT * FROM ' . URLSLAB_URLS_TABLE . ' WHERE ' . $sql_where_http_status . ' (sum_status = %s OR (sum_status =%s AND update_sum_date < %s) OR (sum_status = %s AND update_sum_date < %s)) ORDER BY update_sum_date LIMIT 500', // phpcs:ignore
				$query_data,
			),
			ARRAY_A
		);
		if ( empty( $url_rows ) ) {
			return false;
		}

		try {
			$rsp = Urlslab_Summaries_Helper::get_instance()->fetch_summaries( $url_rows );
			foreach ( $rsp as $summary ) {
				if ( $summary->getSummaryStatus() == DomainDataRetrievalSummaryResponse::SUMMARY_STATUS_AVAILABLE ) {
					return true;
				}
			}
		} catch ( ApiException $e ) {
			if ( 402 === $e->getCode() ) {
				Urlslab_User_Widget::get_instance()->get_widget( Urlslab_General::SLUG )->update_option( Urlslab_General::SETTING_NAME_URLSLAB_CREDITS, 0 );

				return false;
			}
		}

		return false;    // 100 URLs per execution is enought if there was no url updated
	}

	private function init_client(): bool {
		if ( empty( $this->client ) && Urlslab_General::is_urlslab_active() ) {
			$api_key      = Urlslab_User_Widget::get_instance()->get_widget( Urlslab_General::SLUG )->get_option( Urlslab_General::SETTING_NAME_URLSLAB_API_KEY );
			$config       = Configuration::getDefaultConfiguration()->setApiKey( 'X-URLSLAB-KEY', $api_key );
			$this->client = new SummaryApi( new GuzzleHttp\Client(), $config );
		}

		return ! empty( $this->client );
	}
}
