<?php

use FlowHunt_Vendor\OpenAPI\Client\ApiException;

class Urlslab_Cron_Summaries extends Urlslab_Cron {

	public function get_description(): string {
		return __( 'Syncing summaries generated by URLsLab service to local database', 'urlslab' );
	}

	protected function execute(): bool {
		if ( empty( Urlslab_Connection_Flows::get_instance() ) || ! Urlslab_User_Widget::get_instance()->is_widget_activated( Urlslab_Widget_Urls::SLUG ) ) {
			return false;
		}

		global $wpdb;

		$query_data = array();
		$use_index  = '';

		if ( Urlslab_User_Widget::get_instance()->get_widget( Urlslab_Widget_Urls::SLUG )->get_option( Urlslab_Widget_Urls::SETTING_NAME_VALIDATE_LINKS ) ) {
			$query_data[]          = Urlslab_Data_Url::HTTP_STATUS_OK;
			$sql_where_http_status = ' http_status = %d AND';
			$use_index             = ' USE INDEX (idx_sum_cron)';
		} else {
			$sql_where_http_status = '';
		}

		$query_data[] = Urlslab_Data_Url::SUM_STATUS_NEW;
		$query_data[] = Urlslab_Data_Url::SUM_STATUS_ACTIVE;
		$query_data[] = Urlslab_Data::get_now( time() - Urlslab_User_Widget::get_instance()->get_widget( Urlslab_Widget_Urls::SLUG )->get_option( Urlslab_Widget_Urls::SETTING_NAME_SUMMARIZATION_REFRESH_INTERVAL ) );
		// PENDING urls will be retried in one hour again
		$query_data[] = Urlslab_Data_Url::SUM_STATUS_PENDING;
		$query_data[] = Urlslab_Data::get_now( time() - 900 );

		$url_rows = $wpdb->get_results(
			$wpdb->prepare(
				'SELECT * FROM ' . URLSLAB_URLS_TABLE . $use_index . ' WHERE ' . $sql_where_http_status . ' (sum_status = %s OR (sum_status =%s AND update_sum_date < %s) OR (sum_status = %s AND update_sum_date < %s)) ORDER BY update_sum_date LIMIT 10', // phpcs:ignore
				$query_data,
			),
			ARRAY_A
		);
		if ( empty( $url_rows ) ) {
			$this->lock( 300, Urlslab_Cron::LOCK );

			return false;
		}

		try {
			foreach ( $url_rows as $row ) {
				$url_obj = new Urlslab_Data_Url( $row, true );
				if ( ! $url_obj->get_url()->is_url_valid() ) {
					$url_obj->set_sum_status( Urlslab_Data_Url::SUM_STATUS_ERROR );
					$url_obj->update();
					continue;
				}

				Urlslab_Connection_Flows::get_instance()->update_summary( $url_obj );
			}
		} catch ( ApiException $e ) {
			if ( 402 === $e->getCode() ) {
				Urlslab_User_Widget::get_instance()->get_widget( Urlslab_Widget_General::SLUG )->update_option( Urlslab_Widget_General::SETTING_NAME_FLOWHUNT_CREDITS, 0 );
				$this->lock( 300, Urlslab_Cron::LOCK );

				return false;
			} else if ( 429 === $e->getCode() || 500 <= $e->getCode() ) {
				$this->lock( 60, Urlslab_Cron::LOCK );
			}
		}

		return false;    // 100 URLs per execution is enought if there was no url updated
	}
}
